src/app/Trigger/TriggerPost.js, src/post/PostSingleModal.js, src/post/PostSinglePage.js, src/styles/modules/triggers.scss
=> Showing extra info on single post triggers

src/app/Header.scss, src/app/Menu/MenuFeed.js, src/app/Menu/MenuPost.js, src/app/Menu/MenuPost.scss, src/comments/CommentItem.js, src/comments/CommentItem.scss, src/comments/Comments.js, src/comments/Comments.scss, src/comments/CommentsList.js, src/post/PostFeed.js, src/post/PostSingleContent.js, src/post/PostSingleContent.scss, src/post/PostSingleModal.js, src/post/PostSinglePage.js, src/styles/modules/post/post.scss
I've mostly done this:
- Replaced TriggerPost to a footer navigation:
- Improve nested comment render
=> Comment and singlepost enhancements

src/user/UserFeed.js, src/user/UserProfile.js
=> add route to modal props to fix a scroll bug

src/app/Sidebar.js
Following list is being fetched infinitely.
=> Fix infinite request loop

src/comments/CommentForm.js, src/comments/CommentItem.js, src/comments/Comments.js, src/comments/CommentsList.js, src/comments/commentsActions.js, src/comments/commentsReducer.js, src/helpers/stateHelpers.js, src/post/PostSingleContent.js, src/post/postsReducers.js
This PR will restructure the comment state, add the feature of replying to comments and sort the comments based on votes. Still some refinements remained.
Should also fix the sorting of comments, and show the whole comments with replies open in single page views.
Should be merged after #170
=> Comment reply feature

src/app/Header.js, src/app/Header.scss, src/bookmarks/Bookmarks.js, src/feed/feedReducers.js, src/post/PostSingle.js, src/post/PostSingleContent.js, src/post/PostSingleModal.js, src/post/PostSinglePage.js
- Make the bookmark toggle button working on single post page and modal
- Make the update happen instantly when remove a bookmark on /bookmarks page
- Add custom message when no Bookmark (page empty) : "Start adding some Bookmarks!" or a message like that
- Add Text on Header. Because it's not obvious for User experience that you are in Bookmark page, except by URL
=> Bookmark enhancements

src/post/Write/ImageBlock.js, src/post/Write/PostEditor.js, src/post/Write/SideControls.js, src/post/Write/Write.js
=> Support image markdown in editor

src/app/AppSettings.js, src/bookmarks/Bookmarks.js, src/favorites/FavoriteCategoryButton.js, src/helpers/donors.js, src/post/Write/PostEditor.js, src/post/Write/PostEditor.scss, src/post/Write/SideControls.js, src/post/Write/Write.js, src/post/body.js, src/statics/Error404.js, src/styles/modules/form.scss, src/tags/Tag.js, src/user/UserFollowers.js, src/user/UserFollowing.js, src/user/UserProfile.js, src/user/UserTransfers.js
I've mostly improve editor and bookmark render, some small refactor and update donor list.
=> Enhancement

src/post/PostSingleModal.js
Should fix the issue with modals when you click on the same link that you opened the modal from.
=> Fix modal issue

src/app/Menu/MenuPost.js, src/post/PostActionButtons.js, src/post/PostSingle.js, src/post/PostSingleModal.js, src/post/PostSinglePage.js, src/post/postActions.js
This PR should add dislike button on single page with showing the number of Dislikes
=> Dislike button on single page

src/store.js, src/user/TransferHistory.js, src/user/UserTransfers.js, src/wallet/walletActions.js, src/wallet/walletReducer.js
This PR should add transaction history to `@user/transactions` 
Results are integrated with how Steemit is showing them and is implemented to support infinite scrolling but results older than 1 month is not returned from the API
=> Transfer History

src/app/Menu/MenuPost.js, src/helpers/IsScrolling.js
Showing no trigger (MenuPost) while scrolling
=> No trigger scroll

package.json, src/comments/CommentItem.js, src/comments/Comments.js, src/comments/CommentsList.js, src/helpers/stateHelpers.js, webpack/makeConfig.js
should add the sorting ability to comments in single post page. needs style refinement.
=> Comments sort

src/comments/CommentItem.js, src/comments/Comments.js, src/comments/CommentsList.js, src/comments/commentsReducer.js
Should add dislike button on comment items and update optimistically
=> Comment dislike

.eslintrc.js, src/favorites/FavoriteCategoryButton.js, src/feed/Page.js, src/tags/Tag.js, src/tags/Tags.js
also fixed the bug on the page since it wasn't working.
=> Adding Favorite button to /tags page

package.json, src/app/appReducers.js, src/post/Write/EditorReducers.js, src/store.js, webpack/makeConfig.js
some fixes with codebase initial setup and dev tools. commits are self explanatory.
=> Fix setup issues

src/post/Feed/PostFeedList.js, src/post/Feed/PostFeedList.scss
This PR should add bookmark button on List View
=> Bookmark list

src/app/Sidebar.scss, src/app/Sidebar/SidebarTabs.js, src/app/Sidebar/SidebarUsers.js, src/messages/MessagesCategory.js, src/messages/MessagesUser.js, src/messages/messagesActions.js, webpack/makeConfig.js
This PR should fix the send and receive issues in chat and bring back the unread counter
=> Chat issues fix

package.json, src/app/Sidebar.js, src/helpers/apiHelpers.js, src/user/User.js, src/user/UserFollowers.js, src/user/UserFollowing.js, src/user/UserProfile.js, src/user/profileTooltip/ProfileTooltip.js, src/user/userActions.js, src/widgets/Follow.js
=> Remove steemdb

src/post/Write/Write.js, src/widgets/Loading.js, src/widgets/Loading.scss
@adcpm Is this how you expected?
=> Show loading while submitting article

src/messages/messagesActions.js, src/messages/messagesBackground.js
should add tokens to unprotected endpoints
=> Chat auth fixes

src/messages/MessageList.js
=> Sort chat messages correctly

views/user.hbs
Thanks @p0o @liondani. 
Should Fix React-Intl Issue and #217 #304
=> Fix Blank screen bug

src/comments/commentsActions.js
Fix #311 
Ref https://github.com/steemit/steem-js/blob/6ce1a43afa34a5c82509c3f15cf3cbb8642c0f3a/src/broadcast/index.js#L91
=> Don't Stringify JsonMetaData. Already handled by steem-js

src/post/Body.js
=> Markdown fix

src/post/Feed/PostFeedList.js, src/translations/en.json
=> Add time ago indicator on list view

src/app/Menu/MenuPost.js, src/post/Feed/PostFeedCard.js, src/post/PostActionButtons.js, src/post/PostSingle.js, src/post/PostSingleContent.js, src/post/PostSingleModal.js, src/post/PostSinglePage.js
=> remove reblog button on users own posts

src/helpers/regexHelpers.js, src/helpers/steemitHtmlReady.js, src/helpers/steemitLinks.js, src/post/Body.js
Using Html parsing code from steemit. 
Closes #343
=> Markdown fixes

src/auth/RequireLogin.js, src/statics/Error401.js, src/statics/Error403.js, src/translations/en.json
=> Show related message for un-authenticated pages

src/comments/CommentItem.js, src/comments/commentsActions.js
=> Fix the style and position of comment after replying

package.json, src/post/Feed/PostFeedCard.js, src/post/PostFeedEmbed.js, src/post/PostFeedEmbed.scss
This PR uses new changes in [embedjs](https://github.com/adcpm/embedjs) to show the thumbnail on youtube embeds on PostFeed view. there is a play button over thumbs and will transition to youtube iframe embed on click.
=> Thumb first on youtube embeds

src/helpers/steemitHtmlReady.js
=> Fix DomParser begins with html tags

src/comments/CommentForm.js
=> Fix-383 Sending empty body comments

src/helpers/scrollHelpers.js, src/messages/MessageDateGroup.js, src/messages/MessageForm.js, src/messages/MessageGroup.js, src/messages/MessageList.js, src/messages/MessageList.scss, src/messages/MessagesCategory.js, src/messages/MessagesUser.js, src/messages/messagesActions.js, src/messages/messagesReducer.js, src/widgets/InfiniteScroll.js
This closes #373. Implements infinite scrolling for messages with scroll
position compensation after inserting the latest page.
This depends on adcpm/busy-ws#12
=> Add Infinite Scrolling pagination (#373)

src/post/PostFeedEmbed.js, src/post/PostFeedEmbed.scss
should fix #381 and refine the style of play button to looks clear on all types of images
=> Fix fierfox bug in video thumbs

src/messages/MessageList.js, src/widgets/Loading.js
=> Add loading state for messages (#388)

src/app/Menu/MenuPost.js, src/styles/modules/base.scss, src/styles/modules/buttons.scss, src/user/User.js, src/wallet/Transfer.js
These are small changes to make tipping and transfers more easy.
- Added a simple button "Tip the author" in the end of post.
- And a button "transfer" on user profile.
Waiting for your review or suggestions.
=> Simple tipping

src/post/LikesList.js
=> Show dislikes

src/comments/CommentForm.scss
=> Fix comment input hidden by submit button

src/app/Header.scss, src/app/Menu/MenuPost.js, src/post/Feed/PostFeedCard.scss, src/post/PostFeedEmbed.js, src/post/PostFeedEmbed.scss, src/post/PostSingleContent.js, src/post/PostSingleContent.scss, src/post/Reactions.scss, src/styles/modules/base.scss
- Improve design
- Fix youtube thumb
=> Fix youtube thumb

src/post/Write/EditorReducers.js, src/post/Write/SideControls.js, src/post/Write/Write.js
=> Reduce opacity for loading img

src/app/AppSettings.js, src/app/Header.js, src/auth/RequireLogin.js, src/bookmarks/Bookmarks.js, src/feed/Page.js, src/messages/MessagesCategory.js, src/messages/MessagesUser.js, src/post/PostSingleModal.js, src/post/PostSinglePage.js, src/post/Write/Drafts.js, src/post/Write/Write.js, src/statics/About.js, src/statics/Donors.js, src/statics/Error401.js, src/statics/Error404.js, src/statics/Help.js, src/statics/Team.js, src/tags/Tags.js, src/user/User.js, src/wallet/Transfer.js, src/widgets/tooltip/ProfileTooltip.scss, src/widgets/tooltip/SimpleTooltip.scss, src/wrapper.js
One header to rule them all :D. I've removed all Header components on page to use only one on wrapper.js. It's simplify the code and make it easier for future design changes.
=> Header in wrapper

src/helpers/apiHelpers.js, src/helpers/formatter.js, src/post/AuthorBio.js, src/post/Body.js, src/post/PostFeed.js, src/post/PostSingle.js, src/post/PostSingleContent.js, src/post/Write/EditorActions.js
Init formatter.jsonParse method and allow string that have been parsed twice.
Close #419
=> Json parse

src/app/Notification/Notification.js, src/app/Notification/Notification.scss, src/app/Notification/notificationActions.js, src/app/Notification/notificationReducers.js, src/comments/CommentForm.js, src/comments/CommentFormEmbedded.js, src/post/postSingle/PostSingleModal.scss, src/widgets/modal/Modal.scss
- Make single post slider not going over post content
- Add notify context (success) with check icon
=> Modal and notify enhancement

src/app/Notification/Notification.js, src/app/Notification/Notification.scss
=> Add error context on notify

src/feed/Feed.js, src/post/postSingle/PostSingleModal.js
=> fix the bug with exiting modal

src/post/postSingle/PostSingle.js
=> PostModal Fix

src/post/postSingle/PostSingleModal.js, src/post/postSingle/PostSingleModal.scss
=> Change position next and prev buttons

src/widgets/popover/Popover.js, src/widgets/popover/SimplePopover.js
add right and bottom-left view features to popover
=> Popover enhancement

src/post/Feed/PostFeedCardHelper.js, src/post/PostFeed.js
=> Get images from body if not in jsonMetadata

src/widgets/modal/Modal.scss
@mynameisek please check if it fixes #466
=> bug fix #466

src/post/Write/Write.js, src/post/Write/Write.scss
=> handle overflowing title

src/user/TransferHistory.js
adding `fill_order`, `claim_reward_balance ` and `fill_convert_request` operations instead of showing them as JSON.
=> Improving user transfers page

server/app.js, src/feed/Feed.js, src/feed/Page.js, src/feed/PathMatching.js, src/feed/feedActions.js, src/helpers/apiHelpers.js, src/reducers.js, src/user/User.js, src/user/UserFeed.js, src/user/UserPosts.js, src/user/UserProfile.js, src/user/UserReplies.js, src/user/userActions.js, src/user/usersActions.js, src/user/usersReducer.js
Added ServerSide Reload for all Page expect home.
On Home page loggedIn users experiences loading again thats why not enabled for Home Page.
=> Server side for profile and feeds

src/app/AppSettings.js, src/user/UserTransfers.js, src/widgets/UserCard.js
There was an issue on column class on small device, it was not aligned.
=> Fix column class

server/app.js, src/helpers/actionDecorator-spec.js, src/index.js, src/store.js
=> New Store for each request

src/user/UserTransfers.js
Should be merged after https://github.com/adcpm/steemconnect.com/pull/123
=> Ability to Claim reward 

src/comments/CommentItem.scss
=> Add word-break on comment

src/user/UserTransfers.js
@adcpm Can you check? Not able to test have no rewards to claim.
=> Reload Transfer list after claiming reward

src/components/Button/Action.js, src/components/Button/Follow.js, src/components/Button/Topic.js, src/components/Sidebar/StartNow.js, src/stories.js, src/styles/custom.less
This PR will focus only on customizing Ant Design just by overriding less variables. Inconsistences between antd and Busy design will be resolved later with custom classes.
=> Customize antd

src/components/Button/Action.js, src/components/Button/Action.less, src/components/Button/Follow.js, src/components/Button/Follow.less, src/components/Button/Topic.js, src/components/Button/Topic.less, src/styles/custom.less, src/styles/mixins.less
**Topic:**
**Favorite topic:**
**Follow/Following:**
**Action:**
=> Style buttons

src/components/Navigation/Sidenav.js, src/components/Navigation/Sidenav.less, src/components/Navigation/Topnav.js, src/components/Navigation/Topnav.less, src/styles/custom.less
**Guest Topnav:**
**User Topnav:**
**Sidenav:**
=> New navigation

src/store.js
=> Persist only locale, sidebarIsVisible, layout in app

src/components/Navigation/Sidenav.js, src/components/Navigation/Sidenav.less, src/stories.js
Updates #519 
**Sidenav** unlogged:
**Sidenav** logged:
=> Add Sidenav for guest users

src/components/Sidebar/InterestingPeople.less, src/components/Sidebar/StartNow.less, src/components/Sidebar/Topics.less, src/components/Sidebar/User.js, src/components/Sidebar/User.less, src/components/UserHeader.js, src/components/UserHeader.less, src/stories.js, src/styles/common.less, src/styles/custom.less
=> Add UserHeader

src/components/Sidebar/InterestingPeople.js, src/components/Sidebar/InterestingPeople.less
Looks like I missed that one on #514 
**InterestingPeople** component:
=> Add new icon to Interesting people

src/components/UserMenu.js, src/components/UserMenu.less, src/stories.js
=> Add UserMenu component

src/post/BodyShort.js
This should prevent crash when rendering BodyShort with many backslashes
=> Fix backslashbomb

src/components/Story/StoryLoading.js, src/components/Story/StoryLoading.less, src/stories.js
=> Add StoryLoading component

src/components/Button/Follow.js, src/components/Button/Follow.less, src/styles/mixins.less
**Topic** button:
**Follow** button:
=> Update button styles and behavior

src/components/Button/Topic.js, src/components/Button/Topic.less, src/components/Sidebar/Topics.js, src/components/TopicSelector.js, src/components/TopicSelector.less, src/stories.js, yarn.lock
=> Add TopicSelector

package.json, yarn.lock
=> Update Steemconnect package

src/app/Sidebar.js, src/components/UserCard.js, src/components/UserCard.less, src/user/UserFollowers.js, src/user/UserFollowers.less, src/user/UserFollowing.js, src/user/UserFollowing.less
=> Styles for User Card as well as User Followers and Following list.

src/actions.js, src/app/Sidebar.js, src/app/appReducers.js, src/post/PostActionButtons.js, src/post/actionButtons/LikeButton.js, src/post/actionButtons/LikeButton.scss, src/store.js, src/user/userActions.js, src/user/userReducer.js
=> Vote power progress

src/components/Sidebar/LatestComments.js, src/components/Sidebar/LatestRecommendations.js
Used key props to remove test warnings.
=> Updated components LatestRecommendations and LatestComments

src/__snapshots__/stories.test.js.snap, src/components/Avatar.js, src/components/Comments/CommentForm.js, src/stories.js
Use steemconnect for default avatar like img.steemconnect.com. This PR fixes 2 warnings when running tests as well caused by improper proptypes validation.
=> Use steemconnect for default avatar

src/app/Sidebar/index.js
This line caused to print state on every page.
=> Clear console from debug console.log

.eslintrc.js, src/components/PopoverMenu/PopoverMenu.js, src/components/PopoverMenu/PopoverMenu.less, src/components/PopoverMenu/PopoverMenuItem.js, src/components/PopoverMenu/PopoverMenuItem.less
This PR solves error with `itemKey` being `undefined`.
=> Refactor PopoverMenu and solve error related to it

src/__snapshots__/stories.test.js.snap, src/components/Story/PostFeedEmbed.js, src/components/Story/StoryPreview.js
React complained about nested links inside stories with images and embed. This PR removes them but it still has the same functionality as before.
=> Fix nested links in Story

src/components/Story/Body.less
https://trello.com/c/v7iQjgy0/116-fix-editor-preview-picture-overflow
=> Fix image overflow editor

src/vendor/steemitHelpers.js
https://trello.com/c/W5ojy8kB/122-fix-editor-posting-fail
=> Fix posting with editor

src/post/Post.js, src/post/postsReducer.js
https://trello.com/c/1Bj4lnpD/103-single-post-voting-should-not-make-the-whole-post-re-loading
=> Fix post loading

.storybook/storyshots-setup.js, src/components/Sidebar/User.js, src/components/UserCard.js, src/components/UserHeader.js, src/stories/__snapshots__/stories.test.js.snap, src/user/User.js, src/user/UserHero.js, src/widgets/FollowButton.js
- Create `FollowButton`
- Use `FollowButton` in `UserCard`
- Use `FollowButton` in `UserHeader`
`FollowButton` is container component that wraps `Follow` component with logic. It's used in `UserCard` and `UserHeader` and should be used for every place where we need Follow button. It doesn't need anything else than `username` so it should work well without any tinkering.
**Related Trello task:** https://trello.com/c/zD170Bjp/115-enable-follow-buttons-user-card
=> Add FollowButton

src/components/Editor/Editor.js, src/components/Story/Body.js, src/components/Story/Body.less, src/components/Story/StoryFull.js, src/components/Story/StoryFull.less, src/stories/__snapshots__/stories.test.js.snap
`Body` component now has `full` prop that is used to specify if it should render post in full style (like in `Post`) or not (line in `Comment`).
=> Move Post styles to Body

src/app/Sidebar/LeftSidebar.js
https://trello.com/c/tQPAz0Ix/135-remove-from-user-website-text-link
=> Remove trailing slash from user website text

src/styles/base.less, src/styles/modules/popover-layout.less
This PR change all popover menu on smaller screen to a bottom fixed menu like this:
=> Mobile popover

src/components/Button/Follow.js, src/locales/en.json
I'm adding the key `followed` instead of `following` because the key `following` is also used in user menu and it's not translated with the same word in french.
=> Fix following translation

src/Wrapper.js, src/app/AppSettings.js, src/bookmarks/Bookmarks.js, src/components/Hero.js, src/components/Navigation/Topnav.js, src/components/Sidebar/SignUp.js, src/components/UserHeader.js, src/stories/__snapshots__/stories.test.js.snap
- Add steemit.com as default signup and edit profile link
- Add bookmarks and drafts on top nav right popover
- Make layout bookmarks and settings using same container than drafts
=> Add default link

src/app/Sidebar/RightSidebar.js, src/components/Sidebar/GetBoost.js
This PR change the visibility of StartNow component. It will be visible only if user never written a root post.
=> Conditional visibility for StartNow

webpack/makeConfig.js
This make moment integration ligher without breaking time ago sentence in different locales.
=> Setup webpack to ignore moment locale

package.json, src/components/Comments/Comment.js, src/components/Navigation/Notifications/NotificationTransfer.js, src/components/PayoutDetail.js, src/components/Reactions/ReactionsModal.js, src/components/Story/StoryFooter.js, src/components/UserMenu.js, src/components/Utils/USDDisplay.js, src/locales/en.json, src/stories/__snapshots__/stories.test.js.snap, src/tags/Tag.js, src/user/UserTransfers.js, src/wallet/Transfer.js
https://trello.com/c/NZAgv8iL/167-use-react-intl-instead-of-numeral
=> Remove numeral in favour of react-intl

src/app/Sidebar/LeftSidebar.js, src/components/UserHeader.js, src/locales/en.json
=> Change user menu

src/store.js
https://trello.com/c/lps0z1IO/136-fix-localstorage-saving-following
=> Clean localStorage

src/components/Story/Body.less
Improve single post render for columns, code and li, see these:
http://localhost:3000/steemdev/@p0o/introducing-steembot-an-open-source-library-to-easily-create-real-time-automation-on-top-of-steem
http://localhost:3000/news/@permatek/how-silicon-valley-discovered-lsd-arts-and-life-news-part-1
https://trello.com/c/BDZXaAAJ/162-single-post-fix-column-render
=> Improve render of column, list and code

src/styles/modules/variables.less
https://trello.com/c/mJA7V4mR/148-make-sidebars-10px-larger
=> Increase sidebars width by 10px

src/components/Story/Body.less, webpack/webpack-dev-server.js
This changes styles of image inside Body so it mimics Condenser behavior.
https://trello.com/c/z4reaRQH/193-picture-are-not-aligned
=> Update image styles

src/post/Write/editorReducer.js
https://trello.com/c/FXA6kZhe/198-draft-delete-confusing
=> Fix deleting drafts

package.json, src/components/Story/PostFeedEmbed.js, src/components/Story/PostFeedEmbed.less, src/stories/__snapshots__/stories.test.js.snap, yarn.lock
https://trello.com/c/qmdk4UDh/207-single-post-youtube-preview-does-not-fit
=> Fix youtube preview

src/comments/CommentItem.js, src/comments/Comments.js, src/comments/CommentsList.js, src/helpers/isVoteBarEnabled.js, src/post/actionButtons/LikeButton.scss, src/post/postSingle/PostSingle.js
Adds voting power slider to user comments on a post
https://trello.com/c/N5oZYBHo/6-voting-power-slider-on-comment
=> Show voting power bar in comments if enabled for user

src/comments/commentsActions.js, src/comments/commentsReducer.js, src/components/Comments/CommentForm.js, src/components/Editor/Editor.js
https://trello.com/c/Bck2EJsn/158-bug-comment-and-upload-image
=> Fix commit bugs related to images and submitting

circle.yml, src/components/UserHeader.less
https://trello.com/c/ESlSXcnS/212-busy-img-center-cover-picture
=> Center cover image

circle.yml, package-lock.json
This uses `circleci:node:8.4.0` image on Circle and switches from yarn to `npm@5.3.0`.
https://trello.com/c/KNNdlVs8/226-use-npm-instead-of-yarn-on-circleci
=> Use npm in CI

src/Wrapper.js, src/components/Navigation/Sidenav.js, src/components/Navigation/Topnav.js, src/stories/__snapshots__/stories.test.js.snap
This PR add to steemd.com for "activity", open steemit.com for user wallet and google for a search.
=> Add replacement for features not ready

src/components/Comments/Comment.js, src/components/Comments/Comment.less, src/post/PostContent.js
https://trello.com/c/8TgSFcai/105-comment-hash-url-should-scroll-to-comment
=> Scroll to comment with anchor links

src/styles/modules/post-layout.less
https://trello.com/c/OBmNWqXN/228-responsive-padding-left-and-right-on-single-post-and-write-page
=> Add left-right paddings on mobile post-layout

src/components/Navigation/Topnav.js, src/components/Navigation/Topnav.less, src/stories/__snapshots__/stories.test.js.snap
Notifications and more icons had to small boundaries that made it harder to click. This solves this issue.
https://trello.com/c/w2o6io3J/224-topnav-trigger-notification-and-settings
=> Update Topnav icons boundaries

src/components/UserHeader.js, src/stories/__snapshots__/stories.test.js.snap, src/styles/base.less, src/styles/modules/modal-layout.less
Improve render of modal in mobile, remove margin and align in top.
Also changed the trigger for UserHero popover menu to "click"
=> Modal responsive

package-lock.json, package.json
https://trello.com/c/xnoiOoX6/245-feed-fail-to-load
=> Upgrade to embedjs 0.0.9

src/components/Comments/Comment.js
2 depth is little bit too much in small device
=> Limit comment intend to 1 depth

src/components/Hero.less, src/styles/custom.less, src/styles/fonts.less
https://trello.com/c/buipWssp/248-font-not-working-for-some-accent
=> Whitney font missing letters

package.json, src/post/Write/PostEditor.js
- It adds in a fix for image upload in the editor that was previously not working.
- It adds in a fix for markdown shortcuts that was previously not working.
- It adds in a fix for copy paste that was previously not working.
- It adds in a fix for return key that was previously not working.
https://trello.com/c/hItHsFKm/8-fix-editor
=> Fix image upload and markdown editing

package-lock.json, package.json, server/app.js, server/auth-server.js, src/components/Navigation/Topnav.js, src/stories/__snapshots__/stories.test.js.snap
Implement the param "state" with `sc2-sdk` to redirect user back where he was when he hit the link "Login".
https://trello.com/c/nuvdesJn/234-add-next-parameter-on-login-to-keep-url
=> Redirect user to previous busy page after login

src/components/Comments/Comment.js, src/components/Reactions/ReactionsList.js, src/components/Reactions/ReactionsList.less, src/components/Reactions/ReactionsModal.js, src/components/Story/StoryFooter.js, src/components/UserCard.js, src/components/UserCard.less
https://trello.com/c/oe0g8CJD/140-show-reward-in-and-on-vote-list-modal
=> Add $ value and % next to votes

src/components/UserHeader.js
There was an issue with the follow button in user hero. It was sending request to Sc2 to follow the profile name and not the username.
=> Fix follow button

src/comments/Comments.js, src/comments/commentsActions.js, src/components/Comments/Comment.js, src/components/Comments/Comment.less, src/components/Comments/Comments.js, src/components/Comments/EmbeddedCommentForm.js, src/components/Comments/EmbeddedCommentForm.less, src/locales/en.json
https://trello.com/c/Mcv190hq/161-edit-comment
=> Editing comments

.storybook/storyshots-setup.js, src/components/UserMenu.js, src/components/UserMenu.less, src/stories/__snapshots__/stories.test.js.snap, src/styles/modules/feed-layout.less, src/styles/modules/grid.less, src/styles/modules/menu-layout.less, src/styles/modules/post-layout.less, src/styles/modules/topnav-layout.less, src/styles/modules/variables.less
https://trello.com/c/V3EcBYHs/252-implement-mobile-horizontal-scroll
=> Add horizontal scroll on mobile

src/app/Sidebar/RightSidebar.js, src/components/Sidebar/InterestingPeople.js, src/components/Sidebar/InterestingPeople.less, src/stories/__snapshots__/stories.test.js.snap
=> Add refresh button and hide users followed in interesting people block

src/components/Story/Body.less
https://trello.com/c/o9dCX8yb/266-comment-markdown-h2-bigger-than-h1
=> Fix h1 size

src/components/Story/Body.less
It fixes the issue with too big paragraph margins on comment:
https://trello.com/c/s3nVu3jP/278-too-big-bottom-margin-on-comment-p
=> Remove paragraph margins on comment

src/components/UserMenu.less
https://trello.com/c/cCtQSeO7/280-image-not-appear-in-feed-while-appear-in-single-post
=> Add white background to UserMenu

.storybook/storyshots-setup.js, package-lock.json, package.json, src/components/Comments/CommentForm.js, src/components/Comments/CommentForm.less, src/components/Comments/EmbeddedCommentForm.js, src/components/Comments/EmbeddedCommentForm.less, src/components/Editor/Editor.js, src/components/Editor/Editor.less, src/locales/en.json, src/post/Write/Write.js, src/stories/__snapshots__/stories.test.js.snap
https://trello.com/c/XPuJH7wV/150-drag-and-drop-image
=> Add drag'n'drop

src/feed/Page.js
This recalculates sort and category of TopicSelector on mount as well, not only when updating fixing issue with missing topic tag.
https://trello.com/c/6iLCiLNS/275-bug-topic-missing
=> Fix TopicSelector update

src/components/Story/Body.js, src/components/Story/PostFeedEmbed.js, src/components/Story/PostFeedEmbed.less, src/stories/__snapshots__/stories.test.js.snap
This removes thumbnail and disables autoplay in single post.
https://trello.com/c/NksPm24B/286-single-post-youtube-preview-image-should-take-full-width
=> Use raw YouTube embed in single post

src/components/Comments/CommentForm.js, src/components/Editor/Editor.js
https://trello.com/c/wFLcxytV/293-upload-image-bug
=> Disable loading after image upload finished

src/components/UserHeader.js, src/components/UserHeader.less, src/helpers/ranks.js, src/locales/en.json, src/statics/EmptyFeed.js, src/stories/__snapshots__/stories.test.js.snap, src/user/UserHero.js
- Empty feed
- Empty profile
- User ranks
https://trello.com/c/g3r7Kd22/288-translate-rank-and-empty-feed-message
=> Add translations

package-lock.json, package.json
https://trello.com/c/GrFOyxSS/251-wrong-image-preview-and-jsonmetdata-link-image
=> Use embedjs 0.0.10

package-lock.json, package.json, src/post/Write/Write.js
https://trello.com/c/GrFOyxSS/251-wrong-image-preview-and-jsonmetdata-link-image
=> Use marked renderer for extracting images and links

src/components/Comments/CommentForm.js, src/components/Comments/EmbeddedCommentForm.js, src/components/Editor/Editor.js, src/stories/__snapshots__/stories.test.js.snap
https://trello.com/c/4LvkIGOs/321-upload-image-should-show-only-image-to-browse
=> Accept only images for file upload

src/components/Navigation/Topnav.js, src/components/Navigation/Topnav.less, src/stories/__snapshots__/stories.test.js.snap
https://trello.com/c/MqwRi6zT/327-add-beta-text-next-to-logo
=> Add beta text

src/components/Editor/EditorToolbar.js
* https://trello.com/c/C6ZRJfKH/322-translate-heading-123-and-comment-successfully-sent
Fixes: #796
=> Translate heading in post editor

src/components/Story/Story.js, src/components/Story/StoryFooter.js, src/components/Story/StoryFooter.less, src/components/Story/StoryFull.js
* Add Edit link (if own post) to bottom of post based on attached image in Trello Ticket
- https://trello.com/c/OQ9wcT8J/314-edit-link-in-bottom-of-post
=> Add Edit Link to Post Footer

.env.example, server/app.js, src/index.js
Remove hardcoded node url so we can switch to different node easy.
=> Enable STEEMJS_URL config var

src/components/UserHeader.js, src/components/UserHeader.less, src/components/UserHeaderLoading.less, src/stories/__snapshots__/stories.test.js.snap, src/styles/custom.less, src/styles/modules/variables.less, src/user/UserHero.js
* For medium/small screen sizes: keep username on separate lines, and centered.
* Trello: https://trello.com/c/PWPN1ZVS/255-responsive-user-hero-center-avatar-and-bring-name-in-another-line
*
=> Update User Profile Responsive styles

src/post/Write/Drafts.js, src/post/Write/Write.js
* https://github.com/busyorg/busy/projects/6#card-5213714
=> Add lastUpdated param to drafts & Sort drafts by most recent

src/locales/de.json
It said "Will be **sent in in** 7 days"
Now it says: "Will be **disbursed in** 7 days"
=> small translation fix (german)

src/bookmarks/Bookmarks.js, src/helpers/metadata.js
* https://github.com/busyorg/busy/issues/827
=> Add bookmarkDate to bookmark metadata & sort bookmarks by bookmarkDate

src/components/UserCard.js
Solves problem with this warning showing up:
`Warning: Invalid argument supplied to oneOf, expected an instance of array.`
=> Fix UserCard propTypes

src/components/Story/Story.less
See: https://github.com/busyorg/busy/pull/876
=> Removed border-radius and top/bottom border from posts on mobile

src/styles/modules/feed-layout.less, src/styles/modules/post-layout.less, src/styles/modules/settings-layout.less, src/styles/modules/topnav-layout.less
On medium screens there was no padding around the content.
I hope this time there's not much to debate... @bonustrack :P
=> padding fixes

src/components/Story/StoryLoading.less
=> fixed .StoryLoading border/border-radius on small screens

src/components/Sidebar/PostRecommendation.js
Fixes #: https://github.com/busyorg/busy/issues/917
Changes:
- Use Link component
=> Use Link component instead of <a> tags in PostRecommendation component

src/components/Navigation/Topnav.js, src/components/Navigation/Topnav.less, src/stories/__snapshots__/stories.test.js.snap
Fixes #940 
Changes:
- Remove notifications menu item from Topnav as it's currently not implemented and might be confusing
=> Remove notifications from Topnav

src/components/Sidebar/SteemTrendingCharts.js
Fixes # .
https://github.com/busyorg/busy/issues/967
Changes:
- switch conversion in API request to cryptocompare
=> Fix Market Rates for Steem & SBD

src/app/Sidebar/LeftSidebar.js, src/components/Navigation/Sidenav.js, src/components/Navigation/SidenavUser.js, src/components/Navigation/Topnav.js, src/stories/__snapshots__/stories.test.js.snap
Fixes # .
https://github.com/busyorg/busy/issues/979
Changes:
- Move replies to main user sidebar nav
=> Move `Replies` to main user sidebar navigation

src/app/Reblog/reblogActions.js, src/auth/authActions.js, src/comments/commentsActions.js, src/index.js, src/post/Write/editorActions.js, src/post/postActions.js, src/routes.js, templates/production_index.html
Google Analytic integration was not working since we updated to react-router v4. This PR fixes this issue and also switch from Analytics code to Segment code which give more flexibility.
Fixes https://github.com/busyorg/busy/projects/6#card-5480527
Changes:
- Remove Google Analytics code
- Add Segment code
- Link Google Analytics to Segment
=> Remove Google Analytics and add Segment

src/components/Sidebar/PostRecommendation.js, src/components/Story/StoryFull.js, src/locales/en.json
Fixes https://github.com/busyorg/busy/issues/1040 .
Changes:
- Update PostRecommendation & Story Full to both use same comments_count / comment_count translations
=> Update PostRecommendation & Story Full to both use same comments_count strings

src/components/Avatar.js
Fixes # https://github.com/busyorg/busy/issues/1041.
Changes:
- update `Avatar` component imageUrl state property when username is passed to it
=> Add `componentWillReceiveProps` method to Avatar component 

src/styles/common.less
Fixes #1009, #1047.
Changes:
- Removes border around iframes.
=> Remove border on iframe

package-lock.json, package.json, setupTests.js, src/components/Button/__tests__/__snapshots__/Action.js.snap, src/components/Button/__tests__/__snapshots__/Follow.js.snap, src/components/Button/__tests__/__snapshots__/Topic.js.snap, src/components/Sidebar/__tests__/__snapshots__/InterestingPeople.js.snap, src/components/Sidebar/__tests__/__snapshots__/LatestComments.js.snap, src/components/Sidebar/__tests__/__snapshots__/Topics.js.snap, src/components/__tests__/__snapshots__/TopicSelector.js.snap, src/components/__tests__/__snapshots__/UserMenu.js.snap, src/feed/Feed.js, src/user/UserList.js, src/vendor/ReduxInfiniteScroll.js, src/wallet/UserWalletTransactions.js, src/wallet/__tests__/__snapshots__/ClaimReward.test.js.snap, src/wallet/__tests__/__snapshots__/PowerUpTransaction.test.js.snap, src/wallet/__tests__/__snapshots__/ReceiveTransaction.test.js.snap, src/wallet/__tests__/__snapshots__/TransferTransaction.test.js.snap, src/wallet/__tests__/__snapshots__/UserWalletSummary.test.js.snap, src/wallet/__tests__/__snapshots__/UserWalletTransactions.test.js.snap
Fixes #985 
Changes:
- Integrate `ReduxInfiniteScroll` to Busy as vendor component.
- Update `enzyme` and `jest` to work with React 16
- Update React and ReactDOM
=> Update Busy to React 16.1.0

src/components/Comments/Comment.less
Fixes #1075 .
Changes:
- Remove unnecessary negative top positioning for comments text
=> Fix for displaying full reputation score in comments

src/components/StoryFooter/StoryFooter.less
Fixes #1086 .
Changes:
- rotated the dislike icon ( `.StoryFooter__dislike` ) 180 degrees so that the thumb of the icon faces downward :)
Here's how it looks:
=> Fixes dislikes icon in vote modal issue

src/client/wallet/Transfer.js
Issue Description taken from: https://github.com/busyorg/busy/pull/1071
```
Users often do not understand that a memo is REQUIRED when
sending a transfer to an exchange. This pull request includes code that will 
validate the memo field on the transfer form when the "TO" field is that of a known exchange.
```
Changes:
- src/wallet/Transfer.js
-  add validateMemo function and exchangeRegex
=> Add Validation to memo for transfer to exchanges

src/client/components/Avatar.js
Fixes issue with loading default avatars on SSR response
Changes:
- Load real avatar by default
=> Try to load real avatar by default

src/client/user/userActions.js
=> use targetUsername instead of username in userActions

src/client/errorMiddleware.js
=> Update error parsing (#1143)

src/client/components/Avatar.js, src/client/components/Avatar.less, src/client/components/UserHeader.js, src/client/user/User.js, src/client/user/UserHero.js, src/client/wallet/__tests__/__snapshots__/ReceiveTransaction.test.js.snap, src/client/wallet/__tests__/__snapshots__/TransferTransaction.test.js.snap
Fixes #1169
Changes:
- Use div as Avatar
- Use direct link for cover image
**This will work on both current and new image provider solution.**
=> Migrate to new image provider

src/client/routes.js
=> Log initial page view (#1162)

src/client/components/Sidebar/CryptoTrendingCharts.less, src/client/components/Sidebar/InterestingPeople.less, src/client/components/Sidebar/SidebarContentBlock.less
Align manual refresh & fix top right/left border issues
Changes:
- add top right/left border radius to title in SidebarBlockContent
- make title display: flex
- margin-left: auto, refresh icons
=> Align manual refresh & fix top right/left border issues

package.json, src/client/components/Sidebar/CryptoChart.js, src/client/components/Sidebar/CryptoTrendingCharts.less, src/client/helpers/cryptosHelper.js
Fixes #1220.
Changes:
- use react-highcharts
- display charts with locale in x-axis
=> Use HighCharts for Market Sidebar

package-lock.json, package.json
Changes:
- Update package-lock.json
- Set version to 2.2
=> Release 2.2

src/client/components/Story/Body.less, src/client/components/Story/Story.less, src/client/styles/fonts.less
Fixes #1230
Changes:
- Update font-style for post
- Update font-style for post preview
- Update font-style for comments
=> Update font style

src/client/feed/Feed.js
Fixes #1243
Changes:
- Increase Feed load threshold to 1500
=> Increase Feed load threshold to 1500

src/server/handlers/createSsrHandler.js, src/server/renderers/ssrRenderer.js
Fixes #1209 
Changes:
- Add meta tag with `noindex, nofollow` if not running at busy.org
=> Add noindex, nofollow if not running at busy.org

src/client/comments/commentsActions.js
Fixes #1262 
Changes:
- Don't broadcast comment_options when updating
=> Don't broadcast comment_options when updating

src/client/feed/Page.js
Fixes #1248 
Changes:
- Add `noindex` to feed pages.
=> Don't index feed pages

app.json, ecosystem.config.js, src/server/handlers/createAmpHandler.js, src/server/renderers/ampRenderer.js
Changes:
- Check if image is non-null before using it (it causes a lot of unhandledRejections and timeouts).
- Add catch to handle future errors.
- Enable `debug` logs on deployment.
=> AMP error handling

src/client/activity/Activity.js, src/client/bookmarks/Bookmarks.js, src/client/components/Editor/Editor.js, src/client/discover/Discover.js, src/client/invite/Invite.js, src/client/post/Write/Drafts.js, src/client/replies/Replies.js, src/client/search/Search.js, src/client/settings/ProfileSettings.js, src/client/settings/Settings.js, src/client/statics/About.js, src/client/statics/Donors.js, src/client/statics/Error404.js, src/client/statics/Help.js, src/client/statics/Team.js, src/client/wallet/Wallet.js
Fixes #1279 
Changes:
- Add page specific titles to each page.
=> Add page specific titles

app.json
=> Remove trailing comma

src/client/components/CommentFooter/CommentFooter.js
=> Hotfix: Use lodash find instead of native one

src/client/components/CommentFooter/CommentFooter.js
Changes:
- Update Comment vote value calculation.
=> Fix Comment vote value

src/client/components/UserHeader.js, src/client/components/UserHeader.less, src/client/helpers/apiHelpers.js, src/client/locales/default.json, src/client/locales/en.json, src/client/user/User.js, src/client/user/UserHero.js
Add "Follows You" text to user header for users that follow current auth user
Fixes #964
Changes:
- Optimize follows your request made
- display "Follows you" if you use follows you
=> Add "Follows You" text to user header for users that follow current auth user

src/client/components/Story/StoryFull.js, src/client/helpers/parser.js
Fixes #1305 
Changes:
- Safely parse metadata
- Make lightbox failsafe in case image is not loaded.
=> Safely parse jsonMetadata

src/client/components/Comments/Comment.js
Fixes #1308 
Changes:
- Add link to user profile.
=> Add links to user profile in comments

src/client/app/Sidebar/UserInfo.js, src/client/components/Button/Follow.js, src/client/components/Button/Follow.less, src/client/components/Button/Topic.less, src/client/components/Button/__tests__/__snapshots__/Follow.js.snap, src/client/components/Editor/Editor.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/Sidebar/SidebarContentBlock.less, src/client/components/Sidebar/User.js, src/client/components/Story/Body.less, src/client/components/Story/Story.js, src/client/components/Story/Story.less, src/client/components/StoryFooter/Buttons.js, src/client/components/StoryFooter/Buttons.less, src/client/components/StoryFooter/StoryFooter.js, src/client/components/UserCard.js, src/client/styles/custom.less, src/client/widgets/FollowButton.js
=> Design improvements

src/client/components/CommentFooter/CommentFooter.js, src/client/components/StoryFooter/StoryFooter.js, src/client/helpers/user.js, src/client/vendor/steemitHelpers.js
=> Hotfix: Include rate in vote value calculation #1246

src/client/wallet/Transfer.js
Fixes #1306 
Changes:
- Use promise for username check
- Return from validator early (prevent hitting steem API when username is too short/long).
=> Update username validation in Transfer

src/client/settings/Settings.js
Fixes #1327.
Changes:
- Update the way `votingPower` is saved in `componentWillReceiveProps`.
=> Fix updating votingPower in settings

src/client/components/Comments/Comment.less, src/client/components/StoryFooter/Buttons.js
Remove Edit from Story Footer & Update Comment Size
Changes:
- Remove Edit from Story Footer
- Update Comment Size
=> Remove Edit from Story Footer & Update Comment Size

src/client/components/Comments/CommentForm.js, src/client/components/Comments/CommentForm.less, src/client/components/Comments/Comments.js, src/client/components/Comments/EmbeddedCommentForm.js, src/client/components/Editor/Editor.js, src/client/components/Editor/Editor.less, src/client/components/Editor/EditorInput.js, src/client/components/Editor/EditorInput.less, src/client/components/Editor/EditorToolbar.less, src/client/components/Editor/withEditor.js, src/client/post/Write/Write.js
=> Refactor Editor and CommentForms

src/server/renderers/ssrRenderer.js
Fixes #1352 
Changes:
- Replace the character in the PRELOADED_STATE
=> Replace the character that make the SSR crash

src/client/components/Story/StoryFull.js, src/client/components/Story/StoryPreview.js
Fixes #1342
Fixes #1343
Changes
- Add `allowfullscreen` param to iFrame to fix dtube full screen player
- add autoplay & use custom play button similar to feed for single posts
=> Updates for Dtube player on Post/Post Preview

src/server/renderers/ssrRenderer.js
Fixes #1352 
Changes
- replace ls character with new line
=> Fix for SSR Renderer

src/server/renderers/ssrRenderer.js
=> Fix SSR Renderer on stable

src/client/post/Write/editorActions.js
Fixes #1349
Fixes #1350
Changes:
- Add check for auth username with referral in editorActions
=> Add check for auth username with referral in editorActions

src/server/handlers/createSsrHandler.js, src/server/renderers/ssrRenderer.js
Fixes #1371 
Changes:
- Update renderSsrPage header const to use right meta tags
=> Fix for SSR Share Post URL Preview

src/server/handlers/createSsrHandler.js, src/server/renderers/ssrRenderer.js
Fixes #1371 
Changes
- Update renderSsRPage header const to use right meta tags
=> Hotfix: Fix SSR Renderer Share Post URL for stable

src/client/components/HeroBanner.js, src/client/components/HeroBanner.less, src/client/components/Navigation/Topnav.js, src/client/styles/modules/grid.less, src/client/styles/modules/topnav-layout.less, src/client/styles/modules/variables.less
Fixes #1365
Changes:
- Add minimum height to `container` class
- Remove `container` class from topnav and add previous container styles in `topnav-layout`
=> Fix for page not fully visible on load

src/client/helpers/socialProfiles.js, src/client/styles/fonts.less
Fixes #1385 
Changes:
- Add YouTube entry to social profiles.
=> Add YouTube social profile

src/client/helpers/apps.js
Changes:
- Add missing apps in the app.json list
=> Update app list

src/client/components/QuickPostEditor/QuickPostEditor.js
Fixes #1382 
This component differs quite a lot from other editors, so not everything could be extracted.
Changes:
- Extract image upload logic to `withEditor` HOC.
=> Use withEditor HOC in QuickPostEditor

src/client/helpers/cryptosHelper.js
Fixes #1345 
Changes:
- Update `getCurrentDaysOfTheWeek`.
=> Display dates in right order under charts

webpack/makeConfig.js, webpack/webpack-dev-server.js, webpack/webpack.server.config.js
Set steemconnnect.com as default `STEEMCONNECT_HOST` instead of v2.steemconnect.com
=> Set steemconnnect.com as default STEEMCONNECT_HOST

src/client/components/Utils/Affix.js
Fixes #1379 
Changes:
- When scrolling down set position to 0px.
=> Prevent overlapping Affix

src/client/comments/Comments.js, src/client/components/Comments/Comment.js, src/client/components/Comments/Comments.js, src/client/components/Story/Body.js, src/client/components/Story/StoryFull.js, src/client/locales/default.json, src/client/post/PostContent.js, src/client/reducers.js, src/client/settings/Settings.js, src/client/settings/Settings.less, src/client/settings/__tests__/settingsReducer.js, src/client/settings/settingsReducer.js
Fixes #1375 
Changes:
- Add `rewriteLinks` option to `Body`
- Add rewrite links setting
=> Add rewrite links option

src/client/components/Story/Body.js, src/client/helpers/regexHelpers.js
Fixes #1408 
Changes:
- Remove DTube preview from post contents
=> Remove DTube image from post contents

src/server/handlers/createSsrHandler.js
Changes:
- Add `createTimeout` helper function
- Timeout fetchData promises after 5 seconds.
=> Timeout fetchData promises after 5 seconds

src/client/errorMiddleware.js, src/common/constants/errors.js
Fixes #1328 
Error messages returned from APIs are inconsistent so they cannot be parsed reliably. This PR detects common error messages based on some kind of fingerprint and returns relevant error message.
Changes:
- Return error messages based on fingerprint.
=> Detect errors based on their content

src/client/components/Comments/Comment.js, src/client/components/Comments/CommentForm.js, src/client/components/Comments/Comments.js, src/client/components/Editor/EditorInput.js
Fixes #1394 
Fixes #1424 
Changes:
- Clear comment form after submitting.
- Input is cleared only after success.
=> Clear CommentForm after successfully submitting comment

src/client/activity/AuthorRewardMessage.js, src/client/activity/CustomJSONMessage.js, src/client/activity/UserActionMessage.js, src/client/activity/VoteActionMessage.js, src/client/components/Sidebar/PostRecommendation.js, src/client/components/Sidebar/PostRecommendationLink.js, src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/helpers/postHelpers.js, src/client/helpers/regexHelpers.js, src/client/post/Post.js, src/client/post/PostContent.js, src/client/search/SearchResultPostPreview.js, src/common/routes.js, src/server/app.js, src/server/renderers/ampRenderer.js
Fixes #1410 
Changes:
- Support post links without category.
- Replace URL with link with category.
=> Support post links without category

src/client/Wrapper.js, src/client/components/Utils/Redirect.js, src/client/locales/default.json, src/client/reducers.js, src/client/settings/Settings.js, src/client/settings/__tests__/settingsReducer.js, src/client/settings/settingsReducer.js, src/server/handlers/createSsrHandler.js
Fixes #1253 
Changes:
- Add beta checkbox.
- Redirect client-side.
- Redirect server-side.
=> Add Busy beta opt-in

src/client/components/Editor/Editor.js
Fixes #1412
Changes:
- Collect data from form using `getFormValues`.
=> Update collecting data from form

src/client/styles/common.less, src/client/styles/custom.less
Fixes #1451
Changes:
- Use tooltip color outlined in #1451
=> Update tooltip color

src/client/components/Comments/CommentForm.js, src/client/components/Comments/EmbeddedCommentForm.js, src/client/components/Editor/Editor.js, src/client/components/Editor/EditorInput.js
=> Make EditorInput compatible with antd

src/client/feed/SubFeed.js, src/client/feed/feedReducer.js, src/client/helpers/stateHelpers.js
Fixes #1469 
Changes:
- Don't fetch feed contents if it's already loading.
=> Don't load feed if it's already loading

src/client/components/Comments/Comments.js, src/client/components/Comments/Comments.less, src/client/components/SortSelector/SortSelector.js, src/client/components/SortSelector/SortSelector.less, src/client/components/TopicSelector.js, src/client/components/TopicSelector.less, src/client/components/__tests__/__snapshots__/TopicSelector.js.snap
Fixes #822 
Changes:
- Add `SortSelector` component.
- Use `SortSelector` for feed and comments sorting.
=> Make Comments header responsive

src/client/components/Avatar.js, src/client/helpers/getImage.js, src/client/post/PostContent.js, src/client/user/User.js
Fixes #1468 
Changes:
- Add `getAvatarURL` helper function.
- Use `getAvatarURL` for user profile and post metadata images.
=> Use SteemitImages for meta images

src/client/locales/default.json, src/client/wallet/Transfer.js, src/client/wallet/Transfer.less
Fixes #1452 
Changes:
- Display current USD amount of transfer
=> Add USD value in Transfer Modal

src/client/feed/SubFeed.js
Fixes #1510 
Changes:
- Check if the content is empty when displaying EmptyFeed.
=> Check if feed is empty for EmptyFeed

src/client/bookmarks/Bookmarks.js, src/client/components/Story/Story.js, src/client/feed/Feed.js, src/client/feed/StoryContainer.js, src/client/feed/SubFeed.js, src/client/feed/feedActions.js, src/client/helpers/stateHelpers.js, src/client/replies/Replies.js, src/client/user/UserComments.js, src/client/user/UserFeed.js, src/client/user/UserProfile.js, src/client/user/UserReblogs.js
Fixes #1494 
Changes:
- Added StoryContainer.
- Feed now subscribes to its own props.
**Tests:**
=> Refactor Feed

src/client/components/Story/Story.js
Fixes #1531  .
Changes:
- shouldComponentUpdate on Story was not checking for next state, and displayHiddenPost was within the state for the component
=> Fix for NSFW posts preview

src/client/components/Story/Body.less
Fixes #1530 
Changes:
- Use same colors as steemit for quote blocks
=> Update styles for quote block in post body

src/client/components/Story/Story.js, src/client/feed/Feed.js
Fixes ##1546 .
Changes:
- Add extra check for if post is comment & remove required showPostModal on Feed component
=> Fix for User Comments not opening

src/client/components/Button/FacebookShare.js, src/client/components/Button/TwitterShare.js, src/client/helpers/socialProfiles.js, src/client/post/PostModal.js, src/client/post/PostModal.less
Fixes #1551 
Changes:
- add facebook share to PostModal 
- create share helpers
=> Add facebook share to PostModal

src/client/components/Editor/EditorInput.less, src/client/components/Editor/EditorToolbar.js, src/client/components/Editor/EditorToolbar.less
Fixes #1461
Changes:
- Use scroll for small screens for editor
- Update editor design based on mock
=> Update editor styles

src/client/bookmarks/Bookmarks.js
Fixes #1584 
Fixes #1571
Changes:
- Add PostModal to bookmarks page
=> Add PostModal to bookmarks page

app.json, package.json, src/client/index.js, src/server/app.js, src/server/handlers/createSsrHandler.js, src/server/index.js, webpack/makeConfig.js, webpack/webpack-dev-server.js, webpack/webpack.server.config.js, yarn.lock
Fixes #1567 
Changes:
- Remove Sentry and NewRelic.
=> Remove Sentry and NewRelic

src/client/components/Comments/Comment.js, src/client/components/Comments/Comments.js, src/client/helpers/sortHelpers.js
Fixes #1606
Changes:
- Add sort by author reputation to comments
=> Add Sort By Author Reputation

src/client/components/Story/Body.js
Fixes issue where embed would be undefined and pages would break
=> Add check for undefined embed

src/client/helpers/apps.js
=> Add steemhunt to apps.json

src/client/components/Story/Body.js
This is related to and closes #1574
=> Fix rendering of embeds nested in columns

src/client/components/Navigation/Topnav.js
Fix for SSR error - window undefined
=> Fix for SSR error - window undefined

src/client/feed/LetsGetStarted.js, src/client/reducers.js, src/client/user/userActions.js, src/client/user/userReducer.js
Add Follow List Error handler for LetsGetStarted
=> Add Follow List Error handler for LetsGetStarted

src/client/helpers/apps.js
Fixes:
- None
Changes:
- Added [Steem.Place](https://steem.place) app to the list.
=> Added Steem.Place app to the list

src/client/vendor/steemitHtmlReady.js
This closes #1578 and is the solution to steemit/condenser#2576.
=> Fix text rendering when next to youtube link

src/client/components/Story/PostedFrom.js, src/client/helpers/__tests__/postHelpers.js, src/client/helpers/postHelpers.js
Fixes #1617 
Changes:
- return null from component if app is not found
- extracted app parsing from `PostedFrom` component and put it in a helper
=> Fix bug where bullet was being displayed for unknown apps

src/client/helpers/formatter.js, src/client/post/PostContent.js
=> Revert "Add ... to meta description to avoid akward cut-offs"

src/client/components/Story/Body.less, src/client/styles/custom.less
Fixes #1645  .
Changes:
- Change post table background
=> Update post table background

package.json, src/client/Wrapper.js, src/client/app/appActions.js, src/client/components/Editor/Editor.js, src/client/components/Editor/Editor.less, src/client/components/Editor/EditorInput.js, src/client/components/Navigation/Notifications/Notification.less, src/client/components/Navigation/Notifications/Notifications.js, src/client/components/Navigation/Notifications/Notifications.less, src/client/components/QuickPostEditor/QuickPostEditor.js, src/client/helpers/notificationsHelper.js, src/client/locales/default.json, src/client/notifications/NotificationPopup.js, src/client/notifications/NotificationPopup.less, src/client/reducers.js, src/client/styles/common.less, src/client/styles/custom.less, src/client/user/userReducer.js, src/common/constants/notifications.js, yarn.lock
Changes:
- Still a WIP but creating PR to test and get feedback
- Had to upgrade to antd 3.0.0 since I was having trouble with notifications component - https://github.com/ant-design/ant-design/issues/8115
- **Important:** Since I upgraded antd, some components might not function as normal or might be styled weird, I caught a few things that were wrong with the editor due to the upgrade, but there might be more
- Add NotificationPopup Component
- Had to use @withRouter and @injectIntl since `<Link/>` and `<FormattedMessage/>` were not working, 
I guess since the notifications popup gets created outside the react dom tree
=> Subscribe to Notifications & Add Notification Popup

src/client/locales/default.json
Fixes #1614 
Changes:
- add sort_author_reputation to translations
=> add comments sort author reputation to translations

src/client/components/Comments/Comment.js, src/client/components/Comments/CommentForm.js, src/client/components/Comments/Comments.js
Fixes #1653  .
Changes:
- add error check for failed comment submissions
=> Fix for comment input erasing on error

src/client/settings/ProfileSettings.js
Fixes #1656  .
Changes:
- Use Form.createFormField for antd@3.0
=> Fix for edit profile form not filling

src/client/components/Story/DMCARemovedMessage.js, src/client/components/Story/Story.js, src/client/helpers/postHelpers.js, src/client/locales/default.json, src/client/post/Post.js, src/client/post/PostContent.js, src/client/post/PostModal.js, src/common/constants/dmca.json
Fixes #1662 .
Changes:
- Check post to see if it contains a banned author or post id
=> Add dmca.json and check if post contains a banned author or id

src/client/styles/common.less, src/client/styles/custom.less
Fixes #1658 .
Changes:
- update global ant-messages to always be over modals
=> Update antd popup messages z-index

src/client/helpers/postHelpers.js
- add try - catch block when getting app data, since some of the functions could fail
- previously fails on this page - https://busy.org/@oudekaas
=> Fix bug on pages where posted from would fail

src/client/components/Editor/Editor.js
Fixes #1668   .
Changes:
- Add Translations to topics validator in Editor component
=> Add Translations to topics validator in Editor component

src/client/post/Write/Write.js
Fixes #1667 
Changes:
- set upvote setting from nextProps in componentWillReceiveProps in Write component
=> Use current users upvote setting when creating a post

src/client/components/Story/Body.js
=> feat: rewrite busy ipfs links to gateway

src/client/Wrapper.js, src/client/styles/common.less
Fixes #1699 
- Header and content are aligned.
- Modal doesn't cause content to move.
- There is no gap.
=> fix: set header width to 100vw

src/client/wallet/ClaimRewardsBlock.js
Fixes #1695 
Changes:
- Make claim rewards primary action button
=> Update Claim Rewards button to have primary action button styles

src/client/helpers/socialProfiles.js, src/client/styles/fonts.less
Changes:
- Adds Linkedin Social Profile on Settings.
=> Linkedin Profile

src/common/constants/dmca.json
Changes: block this post because of DMCA notice https://busy.org/@fatzer/decore-table-artisanale-de-salon-marocaine-or-dykwr-maedh-alsalwn-almghrby-altqlydyh
=> Add post with DMCA notice

src/client/post/Write/Write.js
Fixes #1705
Changes
- url was not updated for new drafts
=> Fix for drafts not saving correctly

src/client/components/Navigation/Topnav.js
Fixes #1736 
Changes:
- Query search API after 300ms after last text update.
=> feat: debounce search autocomplete by 300ms

src/client/auth/__tests__/authReducers.js, src/client/auth/authActions.js, src/client/auth/authReducer.js
Fixes: #1507 
Now you do not need to wait when you want to log out.
* Added instant logout
* Fixed unit test
=> Add instant logout 

src/client/components/PopoverMenu/PopoverMenu.less
Fixes #1773 
Changes:
- Remove doubled scrollbar from language selector. [Preview](https://streamable.com/vd5pl)
=> Fix displaying language selector scrollbar

src/client/user/UserProfile.js
Fixes #1775 .
Changes:
- Check user blog state is empty before calling getFeedContent
=> Check user blog state is empty before calling getFeedContent

src/client/wallet/walletReducer.js
Fixes #1789 
* Added a check for action count value 0 and 1 since  for some users the last action count is 0 but for others it is 1 (due to bug with steem api ? )
=> Update check for last action count

src/client/wallet/Transfer.js
Fixes #1796
* Use SBD constant in Transfer instead of crypto constants
=> use SBD constant in Transfer

src/client/components/Navigation/LanguageSettings.js
`localStorage` and `navigator` were undefined, so SSR was crashing.
* Fix global checks.
=> fix: update global checks

package.json, src/client/styles/common.less, src/client/styles/fonts.less, src/client/styles/modules/drafts-layout.less, src/client/styles/modules/feed-layout.less, src/client/styles/modules/menu-layout.less, src/client/styles/modules/post-layout.less, src/client/styles/modules/settings-layout.less, src/client/styles/modules/topnav-layout.less, webpack/makeConfig.js, webpack/webpack-dev-server.js, yarn.lock
Fixes #1675 
It should get rid of problem of hot reloading not working or crashing.
* Update to less 3
* Update code to less 3 syntax.
=> chore: update to less 3

src/client/index.js
* prevent SW from registering on development
=> feat: ignore SW on development

package.json, yarn.lock
=> chore: remove react-test-renderer

src/client/components/BBackTop.js
Fixes modal crash on staging.
My previous pull request created a bug which appeared on staging.
=> Fixes modal crash on staging 

src/client/bookmarks/Bookmarks.js, src/client/replies/Replies.js, src/client/user/UserComments.js, src/client/user/UserFeed.js, src/client/user/UserReblogs.js
Fixes #1846 
* Add missing post modals to all Feeds.
=> fix: add missing showPostModal props

src/client/components/Editor/Editor.js, src/client/components/Story/Body.js, src/client/vendor/SanitizeConfig.js
Fixes #1852 
Fixes #1869 
* Don't add exit page URL when creating post.
* Use BusyIPFS link in editor.
=> Update HTML generation

src/client/helpers/commentHelpers.js
Fixes #1874 
Fixes #1885
* Check if window exists
=> fix: missing undefined check

src/client/components/UserHeader.js, src/client/components/UserHeader.less
Fixes #1892 
* Add missing class to Transfer button
Before:
After:
=> fix: transfer button styles

README.md, docs/CONTRIBUTING.md
=> chore: update docs

src/client/components/Story/Body.js, src/client/helpers/regexHelpers.js
Fixes #1900
* Only rewrite known links
=> fix: rewrite only known links

src/client/components/UserHeader.less
Fix for #1903, adds text shadow to follows-you text on mobile.
=> Add text shadow to follows-you text on mobile

src/client/styles/modules/feed-layout.less
Fixes #1917 
Fix Css
Check the homepage
=> Fix the unwanted side padding

src/client/locales/default.json, src/client/settings/Settings.js, src/client/settings/Settings.less
Fixes #1811 by adding the suggested version number to the settings page.
=> Add busy version to settings page

src/client/locales/default.json, src/client/post/Write/editorActions.js
Fixes #2020 
* Make error message less specific, as we can't check what is the issue really.
=> fix: update drafts saving error message

src/client/components/Story/StoryPreview.js, src/client/post/PostContent.js
Fixes #2019 
* handle undefined jsonMetadata
=> fix: handle undefined jsonMetadata

src/client/helpers/regexHelpers.js
Fixes #2085
* Add dashes and dots to usernames.
* Add dashes to permlinks and tags.
=> update rewriteRegex to support dots and dashes in permlinks

package.json
- Update package version to v2.5.6
=> release v2.5.6

src/client/components/Story/StoryFull-nightmode.less, src/client/notifications/NotificationPopup-nightmode.less, src/client/notifications/NotificationPopup.less, src/client/styles/common-nightmode.less
* Fixed/Added nightmode styles
=> Missing nightmode styles

src/client/Wrapper.js, src/client/notifications/EmergencyNotificationPopup.js
Fixes #2116
* Add modal displaying a maintenance message
=> Add Emergency/Maintenance message modal

src/client/Wrapper.js
Looks like steem is stable, @mynameisek has advised me to remove the popup
=> Remove EmergencyNotificationPopup

src/client/app/appActions.js
* Properly calculate SBD rate. (https://github.com/Steemhunt/web/commit/0936803cfd1f011baadf7d5d5530ada2f0d97a65). Thanks @sydneyitguy!
=> fix: rate calculation

src/common/constants/dmca.json
Add thedarkoverlord to censor list
=> Censor thedarkoverlord

src/client/components/UserHeader.js
* Fix typo in transfer message id
=> fix: typo in transfer message id

src/client/Wrapper.js, src/client/components/Navigation/Topnav.js, src/client/store.js
Notifications server is having issues and crashes all the time. This disables notifications on the busy.org
=> tmp: disable notifications

src/client/post/Write/editorActions.js, src/client/styles/common.less
=> fix: skip comment options on edits

app.json, src/client/components/Story/Story.js
* Check `reblogged_by` length.
=> fix: reblog indicator
