busyorg/busy

src/feed/Feed.js
src/feed/Page.js
src/statics/EmptyFeed.js
src/statics/EmptyUserOwnProfile.js
src/statics/EmptyUserProfile.js
src/statics/Error404.js
src/user/UserFeed.js
src/user/UserProfile.js

This PR should show a message for empty feeds

show a message for empty feeds

---

src/post/Write/EditorActions.js

checks if permlink already exists

---

package.json
src/helpers/dateHelpers.js
src/messages/MessageDateGroup.js
src/messages/MessageForm.js
src/messages/MessageForm.scss
src/messages/MessageGroup.js
src/messages/MessageList.js
src/messages/messageGroupHelpers.js

- Uses `react-intl` and a new `dateHelpers` module to separate messages by
date group
- Renames messages components so they make more sense
- Documents the grouping functions
- Simplifies message sorting
- Offsets `startOfDay`s so `react-intl` doesn't need to handle timezones
propertly (which it isn't)

Separate messages by day groups

---

src/app/Sidebar/SidebarUsers.js
src/messages/messagesReducer.js

This closes #306, where channel notifications and private message
notifications were mixed up.

Fix notifications issue #306

---

src/post/PostSingleContent.js
src/styles/modules/headings.scss

Actually when you see an article you will see the author en details first then the post title. It seem more common to show first the title before post information. This is a small PR for change it.

Move post title on top of the page

---

package.json
yarn.lock

Some Youtube thumb was not working on Busy, i've changed the thumb link to a better one on Embed.js and updated to v0.0.4

Fix issue with Youtube thumbs

---

src/widgets/Icon.scss

Should close #445
@adcpm Turn out it wasn't a problem with build. I refactored material-icons CSS into Icon.scss during my work and it was in the end of file making all icon sizes equal to `24px` 😄

fix the issue with css preference for icon sizes

---

src/post/BodyShort.js

Current regex deletes next word on new line that occurs behind url (in this case The is missing).
**Before:**
**After:**
See: https://busy.org/@bitspace for posts with that problem.

Fix URL replace regex

---

src/components/Story/BodyShort.js

New design uses own version of `BodyShort` . This PR integrates #535 fix to that component.

Integrate fix from #535

---

src/components/Story/StoryLoading.less

StoryLoading is missing top margin this adds this to every not-first child StoryLoading.

Add margin to StoryLoading

---

src/components/Navigation/Topnav.js
src/components/Navigation/Topnav.less
src/components/PopoverMenu/PopoverMenu.js
src/components/PopoverMenu/PopoverMenu.less
src/components/Story/Story.js
src/components/Story/Story.less
src/components/Story/StoryFull.js
src/components/Story/StoryFull.less
src/components/UserHeader.js
src/components/UserHeader.less
src/stories.js
src/styles/custom.less

Antd's `Menu` doesn't play nicely with Popovers and is impossible to customize in non-invasive way. This PR adds custom `PopoverMenu` that can be easily styled and doesn't interfere with antd's `Menu`.
**Topnav**:
**Story**:
**StoryFull**:
**UserHeader**:

Add PopoverMenu to collapsed menu

---

server/app.js

Error displayed on visiting non existing user is caused by `getFeedContent`. Currently server returns `error.message` which probably is not ideal. This PR redirects user to `/4o4` after error, but it's not ideal solution as well.
I think we should discuss the way to handle such errors with serverside rendering.

Redirect to /404 after server side error

---

src/__snapshots__/stories.test.js.snap
src/stories.test.js

Stories use relative time so every time tests are being run time doesn't match.
This mocks `Date.now` to always return `1499334522047` so it won't change text in the future.

Mock Date.now for jest tests

---

dist/index.html
package.json
server/auth-server.js
webpack/webpack-dev-server.js
yarn.lock

This PR adds `webpack-dev-server` as a potential replacement for `dev` script (which is broken and not suitable for development).
This PR adds 3 scripts:
1. `dev-server:auth-server` Express.js app that is used for handling `/callback` request
2. `dev-server:client` starts `webpack-dev-server`
3. `dev-server` runs scripts above in parallel.
This removes server bottleneck (100 seconds versus 180) and doesn't require tinkering when starting server (running `yarn run dev` and `yarn run start` to do full rebuild and start properly working server which takes around 290 seconds in total).

Add webpack-dev-server for development

---

src/auth/pushpadHelper.js

It caused 404 error to `getSignature` endpoint.

Do not initialize pushpad without env variables

---

src/styles/modules/feed-layout.less

There was missing `display` property on `leftContainer` and it didn't disappear on smaller screens ([reference](https://busy5-pr-506.herokuapp.com/)).

Add missing leftContainer display property

---

src/__snapshots__/stories.test.js.snap
src/components/Story/Body.js
src/components/Story/Body.less

Code inside `pre` blocks can overflow content and be displayed offscreen.
See example code [there](https://busy5-pr-506.herokuapp.com/steemscript/@fabien/steem-script-an-open-json-standard-for-trusted-workflows-proposal).

Add overflow-y to pre inside story body

---

src/components/Utils/Affix.js

When sidebars have `display: none` property containers are `undefined` causing Affix to throw errors ([reference](https://busy5-pr-506.herokuapp.com/))

Check if containers are not undefined

---

src/components/Utils/ScrollToTop.js
src/feed/Page.js

This PR adds ScrollToTop component per react-router 4 [documentation](https://reacttraining.com/react-router/web/guides/scroll-restoration) and adds it to feed page (which fixes bug with unnatural scrolling behavior).

Scroll to top on feed page

---

src/post/postSingle/PostSingle.js
src/post/postsReducers.js

This PR fixes the issue with loading new posts (earlier it wasn't reloading new posts, displaying same post over and over again).
It adds `postLoading` to `posts` state to display `Loading` component as well.

Fix loading new posts

---

src/styles/common.less

Currently when moving to pages with different layout or when opening modals content moves around because of sidebar width.
This PR gets rid of this problem.

Ignore scrollbar width

---

package.json
yarn.lock

`webpack-dev-server` 2.7.0 got unpublished for some reason.

Rollback webpack-dev-server to 2.6.1

---

config.json
src/app/Menu/MenuPost.js
src/auth/pushpadHelper.js
src/constants.js
src/post/PostActionButtons.js
src/post/actionButtons/LikeButton.scss
src/post/postSingle/PostSingle.js
src/post/postSingle/PostSingleContent.js
src/post/postSingle/PostSingleModal.js
src/post/postSingle/PostSinglePage.js

It adds a voting power slider to the comment view when the `thumbs up` icon is hovered on
Open a post modal and hover on the thumbs up icon, a voting power slider will appear if the user has enough `steem` power.

Add voting power slider to single post view

---

src/post/Write/PostEditor.js

It fixes the issue with the editor that prevented new lines and pasted content from being entered into the editor.
https://trello.com/c/YC85uslJ/7-fix-issue-with-editor-cant-copy-past-or-make-new-line
Open the page to add a new post, you should be able to paste content into the editor as well as enter new lines which was previously causing an error to be thrown in the console.

Add fix for editor that prevented new line and pasting content

---

src/comments/commentsReducer.js
src/components/Story/StoryFooter.js
src/feed/feedReducer.js
src/user/userActions.js

- Update `getUserComments` action and its handlers to use `getDiscussionsByComments`.
- Fix `getMoreUserComments` and its handlers to load new comments properly.
- Display reblog button only if `post.parent_author === ''`.
**Related Trello task:** https://trello.com/c/fhgps3KV/106-page-username-comments-pagination

Fix user comments and hide reblog action for some posts

---

package.json
yarn.lock

It adds `pre-commit` hook so before committing `test` and `lint` are run. If any of them fails (returns with non-zero exit code) commit will be refused. You can prevent this behavior by passing `--no-verify` to `git commit` (but better don't)

Add pre-commit hook

---

src/app/Reblog/reblogActions.js
src/app/appReducer.js
src/comments/commentsActions.js
src/feed/feedActions.js
src/post/Post.js
src/post/postActions.js
src/post/postsReducer.js
src/reducers.js
src/user/userActions.js

If user opens post from feed it uses loaded data from feed instead of loading it again.
https://trello.com/c/48Bm1chr/111-single-post-remove-loading-if-previous-page-is-feed

Add preload to post loading

---

src/app/Sidebar/LeftSidebar.js
src/app/Sidebar/Navigation.js
src/app/Sidebar/RightSidebar.js
src/app/Sidebar/UserInfo.js
src/components/Navigation/Sidenav.js
src/user/User.js

Migrates from using `render` prop to `component` in `Route` to allow passing `match` down the tree (so makes it possible to add `isActive` logic).
Adds `isNews` to determine if `News` should be set to active.
https://trello.com/c/p2Y9zwpI/117-sidebar-left-feed-should-be-active-only-on-homepage-link-overwise-activate-news

Refactor sidebars and add logic to determine if user is on news page

---

src/components/Story/StoryFull.js

It prevents omitting count in `{count} comments` message.
https://trello.com/c/iVpBM69B/191-single-post-fix-label-0-comments

Format comments count

---

src/app/Reblog/reblogActions.js
src/app/Reblog/reblogReducers.js

This migrates `reblog` action to `redux-promise-middleware` so errors are handled properly.
https://trello.com/c/dZoxWRbu/188-post-already-resteemed-load-forever

Update reblogging action and fix error handling

---

src/components/Editor/Editor.js

This adds `originalInput` to `Editor` and uses `resizeTextarea` method after setting values to force height update.
https://trello.com/c/9nsmNYi5/201-editor-body-field-not-autoresize-from-draft

Force body input resize after setting value

---

src/components/Editor/Editor.js

`antd` resizes textarea on user input, but does not when value is changed in code.
This PR adds `resizeTextarea` method on `Editor` and triggers it when image or markdown code is inserted.
This issue on `CommentForm` will be solved in #703.
https://trello.com/c/Amfqay0I/175-editor-add-image-in-last-line-dont-trigger-the-autoresize

Resize textarea after inserting images and Markdown

---

src/comments/commentsActions.js
src/comments/commentsReducer.js
src/components/Comments/Comment.js
src/components/Comments/Comment.less

This PR updates `getComments` action and related reducers to pass `focusedComment` to determine which comment should be focused. This adds `focus` method on `Comment` as well that will be used for focusing comments.
https://trello.com/c/7b72tP44/183-when-comment-success-focus-on-it

Focus comment after posting it

---

src/styles/modules/topnav-layout.less

This PR hide topnav search on mobile and show logo and menu. This help user to login on mobile, before it was not possible to do.

Hide topnav search on mobile and show logo and menu

---

src/components/Comments/Comment.js
src/components/Comments/Comment.less
src/components/Comments/Comments.js

- Adds `Comment__replies--no-indent` class.
- If `depth` (drawn, not logical from API) is higher or equal to 2 replies will stop indenting.
- Works for `@small` devices only.
https://trello.com/c/p21C3QGx/230-responsive-comment-intend-should-have-limit

Limit comment indentation on mobile

---

src/components/UserHeader.js
src/components/UserHeader.less
src/user/User.js
src/user/UserHero.js

https://trello.com/c/tNRzZKi0/190-cover-picture-break-visibility
If an user have a cover image the text in UserHeader will be changed to white with text-shadow. If user dont have a cover color remain as usual.
Close #366

Fix cover text visibility

---

src/components/Story/StoryPreview.js
src/helpers/image.js
src/vendor/steemitHtmlReady.js

Some picture was failing due to a limitation from Cloudinary. The Cloudinary proxy image accept only image url with a maximum of 256 char. On this PR i switch to Steemit proxy image when url is longer than 256 char.
See: https://trello.com/c/t3paCZIc/199-busy-img-long-url-picture-fail-to-load
I've spoted another image that fail to load but not sure what is the reason, i created a new Trello card for it https://trello.com/c/ZSnnV6bG/265-busy-img-some-url-fail

Add image proxy helper

---

src/post/Post.js
src/post/Write/editorReducer.js

This removes `editedPost` on `GET_CONTENT_SUCCESS` action. Loading is only shown when there is not content yet or when there is content, post is fetching and it was edited.
https://trello.com/c/SgKH6et1/272-single-post-bug-when-upvote-content-loading

Prevent reloading after upvoting post

---

src/app/Sidebar/UserInfo.js

It fixes user bio not breaking properly.
https://trello.com/c/EswlWbJ3/262-user-profile-about-goes-out-of-the-frame

Add wordBreak to UserInfo

---

src/components/Story/Body.less

This adds clearfix after `Body` and applies `clear: both` to `hr` as condenser does.
https://trello.com/c/GXzS4HlW/260-single-post-render-bug

Add clearfix

---

src/components/Story/PostFeedEmbed.less
src/components/Story/Story.less

This PR adds `max-height` to `400px` for embeds (same as for images) to prevent showing too long Stories in feed:
`video` has been styled as well to prevent the same problem:
https://trello.com/c/zMkJ44dw/258-add-max-height-to-dtube-thumb

Style DTube videos

---

src/components/Story/Body.less

This fixes issue with lists, clears `Body` styles and adds some functionality from Condenser (`.text-justify`, `.text-right`, `.text-center`, .text-rtl`).
https://trello.com/c/JfAn2V0Z/269-list-number-bug-alignement

Update styles to make Busy consistent with Condenser

---

src/components/Navigation/Notifications/Notifications.js
src/locales/en.json
src/post/Write/Write.js

This adds missing `See All` and image uploading notifications text.
We have notifications in action creators as well but it is impossible to use `react-intl` from there.
It's possible to use it statically like [this](https://github.com/yahoo/react-intl/issues/41#issuecomment-227268578), but it doesn't fit our code base (we would have to pass `intl` into `redux-thunk` when creating store, but we won't be able to create `IntlProvider` because we store locale in store. This won't allow changing language as well). We might want to migrate to platform agnostic API like [counterpart](https://github.com/martinandert/counterpart)  - same as Condenser. However, I don't think that's priority right now.
https://trello.com/c/FUq0MJgH/241-translate-see-all-and-uploading-image-and

Add See All and image uploading notifications translations

---

src/comments/commentsActions.js

This fixes issue with comments not reloading after commenting on comment displayed as single post + makes reloading comments more efficient by reloading parent not root comments.
https://trello.com/c/sqhK9jpK/292-bug-commenting-with-comment-link

Reload comments for parent post only

---

src/components/Story/Body.less

- Fix issue with table columns being rendered differently from Condenser.
- Style Body hr (fixes issue with not sufficient space between heading and text).
https://trello.com/c/TFoyyx1G/299-single-post-render-columns-title-hr

Fix table layout and hr style

---

src/components/Editor/Editor.less

Fixes issue with error message overlapping editor
https://trello.com/c/xhdS5lhK/309-edit-post-tag-text-overflow

Replace margin with padding for .ant-form-item

---

src/components/Story/StoryHelper.js
src/components/Story/StoryPreview.js
src/stories/__snapshots__/stories.test.js.snap

https://trello.com/c/GhXYpH1q/313-video-not-showing-on-feed

Display embed and text for short posts

---

src/locales/de.json

German grammar fix from https://github.com/busyorg/busy/pull/870 and https://github.com/busyorg/busy/pull/855. Was overridden in https://github.com/busyorg/busy/pull/873 (https://github.com/busyorg/busy/pull/873/commits/e67ce5fb53da1cc204b71c1157881f2bc16b0adf).

german grammar fix

---

src/components/Story/StoryFooter.js
src/styles/common.less

I saw this was tagged as a good first issue so I decided to take it on.
The original issue, making the users clickable in the tooltip, is of course very straightforward.
However I had to dig into some of the specifics of the LESS precedence order to get the desired behavior in the file that seems to be the place designated for a LESS override on AntDesign's rules.
Here's what I ran into:
- Adding a `<Link>` to the tooltip expectedly renders to an `<a>` tag
- AntDesign's antd.less defines the `@link-color` to be our @primary-color, which is `@purple`
- We override antd.less's `@tooltip-bg` to also be `@purple`
- Therefore, when the link renders, the text becomes invisible since both the `@link-color` and `@tooltip-bg` are `@purple`. Furthermore, we obviously want `@link-color` to remain …

Fix for #869: Be able to click on voted Users

---

src/post/Write/editorReducer.js
src/user/userReducer.js

This PR removes uncovered cases (related to old file upload functionality) in user and editor reducers, and removes any state properties that they referenced, so there are no warnings about not existing imports.
This error:
```
/node_modules/css-loader!./node_modules/postcss-loader/lib?{"ident":"postcss","plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js!./src/styles/base.less
(Emitted value instead of an instance of Error) autoprefixer: /home/sekhmet/Workspace/busy/src/styles/base.less:13206:3: Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rules.
```
is caused by bug in antd and was already fixed in 3.0 alpha (so it will go away after upgrading).

Remove uncovered branches related to file upload

---

src/components/Avatar.js
src/stories/__snapshots__/stories.test.js.snap

* When img.busy randomly goes down, we need to replace avatar with a default avatar
* Add onError handler to img tag
@Sekhmet @bonustrack - this is a possible solution to when `img.busy` randomly goes down. What default avatar url should I use?

Add Avatar image error handler

---

src/app/Sidebar/RightSidebar.js

Fixes # https://github.com/busyorg/busy/issues/915
Changes:
- check for showPostRecommendation flag in RightSidebar

Hide Interesting People for single post pages

---

src/components/StoryFooter/Buttons.less

Fixes #933
Changes:
- Use `#99aab5` for default link color
- Remove transition so colour change matches icon transition

Change Buttons__link color and transition

---

src/app/Sidebar/RightSidebar.js
src/vendor/steemitHelpers.js
src/wallet/ClaimReward.js
src/wallet/PowerUpTransaction.js
src/wallet/ReceiveTransaction.js
src/wallet/SavingsTransaction.js
src/wallet/TransferTransaction.js
src/wallet/UserWalletSummary.js
src/wallet/Wallet.js
src/wallet/__tests__/ClaimReward.test.js
src/wallet/__tests__/PowerUpTransaction.test.js
src/wallet/__tests__/ReceiveTransaction.test.js
src/wallet/__tests__/TransferTransaction.test.js
src/wallet/__tests__/UserWalletTransactions.test.js
src/wallet/__tests__/__snapshots__/ClaimReward.test.js.snap
src/wallet/__tests__/__snapshots__/PowerUpTransaction.test.js.snap
src/wallet/__tests__/__snapshots__/ReceiveTransaction.test.js.snap
src/wallet/__tests__/__snapshots__/TransferTransaction.test.js.snap
src/wallet/__tests__/__snapshots__/UserWalletSummary.test.js.snap
src/wallet/__tests__/__snapshots__/UserWalletTransactions.test.js.snap

Fixes # .
- https://github.com/busyorg/busy/issues/935#issuecomment-340457245
- https://github.com/busyorg/busy/issues/930
Changes:
- Add SteemTrendingCharts to User Wallet Pages & display delegated SP
- Update order of Wallet Summary to "STEEM SP SBD"
- Update Tests & Snapshots

Add SteemTrendingCharts to User Wallet Pages & display delegated SP

---

src/locales/en.json

Fixes #  https://github.com/busyorg/busy/issues/974
Changes:
- page_forbidden and page_forbidden_message referenced in `Error401 component`(https://github.com/busyorg/busy/blob/new-design/src/statics/Error401.js) are both missing translations

add page_forbidden and page_forbidden_message in translations

---

src/components/TopicSelector.js
src/components/TopicSelector.less
src/stories/__snapshots__/stories.test.js.snap

Fixes #988.
This changes how TopicSelector behaves on smaller screens.
- TopicSelector items are now aligned in center
- "Sort by" and current sort now have white-space set to nowrap to prevent
breaking it.
- "Sort by" and current sort now have display set to inline-block to
cause them to split to two lines if there is no room.
**Before**:
**After**:

Update TopicSelector styles

---

src/index.js

Fixes #845
This solves problem with Busy not working in IE11. It works on production builds, not on development builds.
Supporting IE < 11 is more problematic, because of the lack of Web Cryptography API. I don't think we should try to make it work on IE 10 and below as it is not used anymore, insecure and using polyfills for something as important as cryptography might introduce vulnerabilities.
Changes:
- Add `babel-polyfill` to the entry of the app.

Add babel-polyfill

---

src/locales/en.json
src/settings/Settings.js

* https://github.com/busyorg/busy/issues/987
Fixes # .
https://github.com/busyorg/busy/issues/987
Changes:
- Use intl format for "Save" text in User Settings page

Add Save Translation

---

src/wallet/UserWalletTransactions.js

Fixes #1000
- Users such as @inoue, weren't able to get their wallet page to load (https://busy.org/@inoue/transfers)
Changes:
- add isEmpty check to `getFormattedTransactionAmount` in `UserWalletTransactions` since `cancel_transfer_savings` action doesn't include the amount param

Add empty check for cancel transfer savings transaction

---

src/post/Write/Write.js

Fixes #914 
Changes:
- If draft has metadata already it will be merged into new metadata. Topics, images, users, and links will be updated anyway to match current content.

Merge previous jsonMetadata when saving post

---

src/components/Story/StoryHelper.js
src/components/Story/StoryPreview.js

Fixes #1012.
Changes:
- Show image preview if post is short and has an image (similar to embed).

Display image preview for short posts with image

---

src/components/Navigation/Sidenav.less

Fixes #950 .
Changes:
- the left menu (`.Sidenav`) link color changes on hover. `@purple` is set as color for '.Sidenav>li>a:hover'

Changes Sidenav link color on hover #950

---

src/components/Story/StoryFull.js

Fixes #1010.
Save and edit actions missed post as argument causing those
two functions to break.
Changes:
- Now post is passed as argument to `onSaveClick` and `onEditClick`

Fix StoryFull actions: save and edit

---

src/components/UserHeader.less

Fixes #842 .
Changes:
- made `.UserHeader__user` to have `margin: 0 !important;` on small screens. This margin has no relevance on small screens, since the text is center aligned and has no elements on the sides.
- decreased font size for `.UserHeader__user__username` to `28px` on small screens
Observations:
The `!important` was necessary because some media queries were defined before normal style in `UserHeader.less`. Normally media queries are defined after the normal style(non-media). In the present case the normal style would override the media queries, therefore `!important` was needed.
I wanted to move the media queries at the bottom of the file, so that the `!important` will not be needed, but wasn't sure if the reason for this would be clear enough.
In case this is wanted, it can …

Fix reputation wrap issue on mobile #842

---

src/wallet/ClaimRewardsBlock.js

Fixes # https://github.com/busyorg/busy/issues/1024.
Changes:
- Update ClaimRewardsBlock component to use right action for retrieving users account history
- Use `getUserAccountHistory` action instead of `getUserTransactions`

Update ClaimRewardsBlock component to use right action

---

src/auth/authActions.js
src/auth/authReducer.js
src/wallet/ClaimRewardsBlock.js

Fixes # https://github.com/busyorg/busy/issues/1034.
Changes:
- Add updateAuthUser action, and call it when rewards has been successfully claimed

Update current auth user, when claim rewards is clicked

---

src/components/Comments/Comments.less

Fixes https://github.com/busyorg/busy/issues/1037
Changes:
- Add flex-wrap to Comments Header

Add flex-wrap to Comments Header

---

src/components/Story/StoryDeleted.js
src/components/Story/StoryDeleted.less
src/components/Story/StoryFull.js
src/feed/Feed.js
src/helpers/postHelpers.js
src/locales/en.json

Fixes #906.
Changes:
- Add `isPostDeleted` helper that detects if post is deleted (`body` and `title` equal to `deleted`).
- Hide deleted posts in feed.
- Display `StoryDeleted` component instead of content if post has been disabled in single post view.

Handle deleted posts

---

src/helpers/sortHelpers.js

Changes:
1. Remove `parseInt` from `sortVotes`.
Using implicit conversion is faster (~20 times faster). This results
in ~1300ms faster render when scrolling in feed and loading new posts twice:
Before:
After:

Improve votes sorting

---

src/components/Story/Body.less

See here: `/report/@hien-tran/the-best-steem-blockchain-apps-updated-on-09th-november`
Fixes #1058
Changes:
- Add word-break: normal styles to all td/th table tags
- Add display: block to table so we can view the overflow when it gets too large for the post

Add styles to fix table in Post

---

src/components/PopoverMenu/PopoverMenuItem.less

Fixes #1032 .
Changes:
- made the menu items to not wrap text
I tested this and as @espoem said when reporting the issue, this can only be replicated when resizing the page.
If you refresh the page at any window width the text will look good. Therefore the solution for this is as simple as forcing the text to not wrap at all.

Fix for logout localized text wrap issue

---

src/components/Reactions/ReactionsList.js
src/components/UserCard.js

Fixes #1080 .
Changes:
- moved `alt` prop's elements from `/components/Reactions/ReactionsList.js` to `/components/UserCard.js` because of a PropType warning where `alt` prop was sent as `object` but a `string` type was expected (screenshot below)
- removed the restriction to only show vote info for votes with the value greater than `0.1`. This way users can see all the votes information, including the downvotes information (as reported in the 1080)
Screenshot of local (`dev-server`) PropType warning that comes once you click to show the votes modal:

Fixed PropType warning and show all vote stats in modal

---

src/client/components/Avatar.js

Fixes #1136 
Changes:
- Load avatar in `componentDidMount` instead of `componentWillMount`.

Don't load avatars on server

---

src/client/Wrapper.js
src/client/app/appReducer.js
src/client/auth/authActions.js
src/client/auth/authReducer.js
src/client/bookmarks/bookmarksReducer.js
src/client/post/Write/editorReducer.js
src/client/settings/settingsReducer.js

This fixes issue with SSR preventing user to sign in.
Changes:
- Add `meta.refresh` to action to inform reducers that this is refresh and doesn't contain reducer.
- If `meta.refresh` is set to true don't update state.

Check if LOGIN is a refresh

---

src/client/components/QuickPostEditor/QuickPostEditor.js

Fixes #1153 .
Changes:
- add space to post body for posts with no pics since we are using title to create the post for quick post creation

Add space to post body for empty posts to fix Quick Post Creation

---

src/client/user/userActions.js

Fixes #1145 
Fixes #1148 
Changes:
- use targetUsername instead of username in userActions

use targetUsername instead of username in userActions

---

src/client/post/Write/editorActions.js

The default value for `percent_steem_dollars` was set to `5000` while it should be set to `10000` to get the maximum of SBD (50%). The default value were not currently used in `stable`.

Fix default percent_steem_dollars value

---

src/client/routes.js

Should fix recent drop in statistics. Before it didn't send `pageview` event on initial load.
Changes:
- Send `pageview` on initial load

Log initial page view

---

src/client/app/Sidebar/RightSidebar.js
src/client/components/Sidebar/CryptoChart.js
src/client/components/Sidebar/CryptoTrendingCharts.js
src/client/components/Sidebar/CryptoTrendingCharts.less
src/client/components/Sidebar/FeedSidebar.js
src/client/components/Sidebar/SteemTrendingCharts.js
src/client/components/Sidebar/SteemTrendingCharts.less
src/client/helpers/cryptosHelper.js
src/client/wallet/UserWalletTransactions.less
src/common/constants/cryptos.js

Fixes #1170
Changes:
- Add FeedSidebar component & CryptoTrendingCharts component
- add cryptosHelper to search for cryptos within the top 100 crypto constants

Add market price on feed for every crypto

---

src/client/vendor/steemitHelpers.js

HotFix
- Fix for create post, steem.api is redundant causing create posts to fail
Changes:
- remove extra steem.api

Fix for create post, steem.api is redundant causing create posts to fail

---

src/client/feed/feedActions.js

This fixes issue with wrong feed appearing when no tag is specified.
We have to send request with no `tag` at all, to get content from everywhere.
Changes:
- Send empty tag if none is specified.

Fix all feed

---

src/client/post/Post.js
src/client/post/postActions.js
src/client/post/postsReducer.js
src/client/reducers.js

Fixes #1206 
Changes:
- Make posts loading state scoped to certain post.

Make posts loading state scoped to certain post

---

src/client/activity/UserActivitySearch.js
src/client/activity/UserActivitySearch.less
src/client/components/Icon/Loading.less
src/client/components/Sidebar/CryptoChart.js
src/client/components/Sidebar/CryptoTrendingCharts.js
src/client/components/Sidebar/CryptoTrendingCharts.less
src/client/components/Sidebar/InterestingPeople.js
src/client/components/Sidebar/InterestingPeople.less
src/client/components/Sidebar/InterestingPeopleWithAPI.js
src/client/components/Sidebar/PostRecommendation.js
src/client/components/Sidebar/PostRecommendation.less
src/client/components/Sidebar/SidebarContentBlock.less
src/client/components/Sidebar/__tests__/__snapshots__/InterestingPeople.js.snap
src/client/helpers/cryptosHelper.js

Fixes #1211.
Changes:
- Update all sidebar blocks with content (crypto charts, interesting people, post recommendation) to use same styles for class name for background, title, icon and divider
- Also update cryptosHelper - getCryptoDetails to find exact matches for posts tagged with crypto
- Also update loader styles to always be purple

Create SidebarContentBlock.less styles and apply it to all sidebar

---

src/client/wallet/UserWalletTransactions.js
src/client/wallet/UserWalletTransactions.less
src/client/wallet/__tests__/__snapshots__/UserWalletTransactions.test.js.snap

Use Padding instead of Margin for Loader Container in UserWalletTranactions
Fixes:
Activity Loader with no padding in UserWallet see `/@busy.witness/transfers`
Changes:
- use padding instead of margin

Use Padding instead of Margin for Loader Container in UserWalletTranactions

---

src/client/comments/commentsActions.js

Fixes #1213 
Changes:
- Add `broadcastComment` function that broadcasts `comment` and `comment_options` operations

Disable curation rewards on comments

---

src/client/post/postsReducer.js

Fixes #1222 
Changes:
- Mark post as loaded from feed.

Update posts state from feed

---

src/client/app/appActions.js
src/client/app/appReducer.js
src/client/components/StoryFooter/StoryFooter.js
src/client/helpers/user.js
src/client/vendor/steemitHelpers.js

Fixes #1057 
Changes:
- Multiply calculated value by current rate.
- Get rate using `get_current_median_history_price`.

Include rate in vote value calculation

---

src/client/post/postsReducer.js

This is hotfix for #1240 
Changes:
- Don't update post state after liking.

Don't update post state after liking. Fixes #1222

---

src/server/renderers/ampRenderer.js
templates/amp_index.hbs

Fixes #1257
Changes:
- Convert `iframes` to `amp-iframes`.
- Check for `metadata.image` properly.

Support iframe for AMP pages

---

app.json

Trailing commas make JSON files not correct. This breaks Heroku deployments.
Changes:
- Remove trailing comma from app.json.

Remove trailing comma

---

crowdin.yaml

Change default translation file from `en.json` to `default.json` on Crowin config file

Change default translation file

---

crowdin.yaml

Use full locale instead of country prefix for translation file

Use full locale instead of country prefix

---

src/client/post/Write/Write.js

Poor's Man SegWit.
Changes:
- Limit links in metadata to 10 so we don't increase TX size potentially (and practically) creating TX that is bigger than block size.

Limit links to 10

---

src/client/components/CommentFooter/CommentFooter.js

Fixes #1119
- Import lodash's `find` instead of using native one.

Use lodash find instead of native one

---

src/client/components/Avatar.js
src/client/components/AvatarLightbox.js
src/client/components/UserHeader.js

Fixes #1302.
Changes:
- Avatars now use SteemitImages instead of BusyIMG.
- Lightbox uses large avatar from SteemitImages.

Migrate avatars to SteemitImages

---

src/client/settings/Settings.js

Fixes #1239 
Changes:
- Default `showNSFWPosts` to `false` instead of `null`.
- Set `showNSFWPosts` on mount.

Make showNSFWPosts default to false

---

src/client/components/Story/StoryPreview.js

Fixes #1319 
Changes:
- Remove alt tag on image preview to be an empty string, instead of the word "post"

Fix for preview image not found

---

src/client/search/searchActions.js
src/client/search/searchReducer.js

Fixes # 
Sometimes AskSteem is down, causing search to completely fail and not rely on steem for other results. See here https://staging.busy.org/search?q=jm90mm vs this PR
Changes:
- Add catch block for askSteem to return an empty array rather than throw an error

Add error check incase asksteem fails for search

---

src/client/auth/authActions.js
src/client/components/Comments/Comment.less
src/client/components/Sidebar/PostRecommendation.less
src/client/components/TopicSelector.js
src/client/components/__tests__/__snapshots__/TopicSelector.js.snap

Fixes #1373.
Changes:
- Remove promoted from TopicSelector
- Fix for comment collapse icon visibility (Remove negative top styles)
- Fix for PostRecommendation title from overflowing (Add max-width to post-title for flex-wrap)
- Add error checks for SteemConnectAPI.me for timeout

Remove promoted from TopicSelector, Style Updates, Error Checks to SC2.me

---

src/client/Wrapper.js
src/client/auth/authActions.js
src/client/user/userActions.js

Fixes #1387 
Changes:
- Call `login` always for side-effects.
- Dispatch `GET_FOLLOWING_ERROR` instead of throwing.

Always call login for side-effects

---

src/client/Wrapper.js
src/client/styles/common.less

Fixes #1293 
Changes:
- Set Topnav z-index to 1050 (popover has z-index of 1030)
- Set tooltip z-index to 1060.

Update Topnav and tooltip z-index

---

package.json
src/client/components/Story/StoryFull.js
src/client/components/Story/StoryFull.less
src/client/helpers/parser.js
src/client/post/Write/Write.js
yarn.lock

Fixes #848 
Fixes #829 
Fixes #1366
Changes:
- Don't open images that are direct child of link.
- When generating post metadata use regex to extract links and images (current solution ignores HTML links and images).
- Use regex to extract images from post instead of using metadata as it might be incomplete (e.g. this post is missing images in metadata so lightbox won't open: https://staging.busy.org/piston/@xeroc/piston-web-first-open-source-steem-gui---searching-for-alpha-testers)

Generate accurate metadata and refactor image lightbox

---

src/client/components/Comments/Comments.js
src/client/components/Comments/Comments.less

Fixes #1421 
Changes:
- Set default colour for sort back to grey.
- Use OLDEST sort if comments have no votes.

Use OLDEST sort if comments have no votes

---

src/client/components/Comments/Comment.js
src/client/components/Comments/Comment.less
src/client/components/Story/Story.js
src/client/components/StoryFooter/Buttons.js
src/client/feed/Feed.js
src/client/post/PostContent.js

Fixes #963 
Changes:
- Update `RE` display (it wasn't showing on some comments).
- Update `Comment` styles to display focus shadow properly.
- Allow editing comments on `@username/comments` page.
- Allow editing comments when viewing it as single post: `/test/@hellosteem/re-hellosteem-re-hellosteem-re-hellosteem-6ekdcf-test-20180130t123425216z`

Allow editing comments from within feed

---

src/client/comments/commentsActions.js
src/client/components/Comments/Comment.js
src/client/components/Comments/Comments.js
src/client/locales/default.json

Fixes #1422 
Changes:
- Translate `Comment submitted successfully` message.
- Add `Comment updated` message.

Translate comment notifications

---

src/client/components/Avatar.less

Fixes #1374 
Fixes #1433 
We could add add background colour, but it doesn't look well when using avatars with transparency or round avatars. I created version of avatar that work with backgrounds, but with bigger number of comments (~100) it takes 6 seconds to dispatch and handle all the events).
Changes:
- Add border to Avatars.
- Make Avatars circles.

Add border to avatars and make them circles

---

src/client/components/Comments/Comments.js

Unbound `handleSubmitComment` prevents users from sending comments.
Changes:
- Bind `handleSubmitComment`.

Bind handleSubmitComment

---

src/client/components/Story/StoryFull.js
src/client/locales/default.json
src/client/post/Post.js
src/client/post/PostContent.js
src/client/post/Write/Write.js
src/client/settings/ProfileSettings.js
src/client/settings/Settings.less

Fixes #1436 
Changes:
- Add Signature tool to user profile settings
- Include signature in user posts.
I couldn't really test it on real signature stored in profile settings, because I don't have active key for hellosteem, and I didn't want to post using my account.

Add Signature tool to profile settings

---

src/client/user/UserHero.js

Fixes #1472 
Changes:
- Drop trailing commas when building UserMenu links.

Support trailing slash in UserMenu

---

src/client/components/Editor/Editor.js
src/client/helpers/improve.js
src/client/post/Write/Write.js

Fixes #1467 
Changes:
- Add `improve` helper that we can use to add custom tags.
- Add `[+]latex[+]` tag to render LaTeX using Codecogs.
- Improve post preview and final contents when submitting.
To add LaTeX to post you can use custom tag:
```
[+]Latex there[+]
```
like this:
```
[+]
f(x) = \int_{-\infty}^\infty
\hat f(\xi)\,e^{2 \pi i \xi x}
\,d\xi
[+]
```
Post preview: http://localhost:3000/@hellosteem/testing-custom-latex
This is just custom tag, that will be replaced when adding post so it will work in other clients as well.

Add custom tag for latex

---

package.json
yarn.lock

Fixes #1465 
It took a while to figure out why suddenly `sanitize-html` became so big. As it turns out it was small when installed with npm, but got way bigger when installed with yarn. It has `PostCSS@6` dependency, which `npm` somehow "ignores", but yarn doesn't.
Author of sanitize-html suggest it doesn't make sense to use sanitization in the browser, so he doesn't care about its size, and recommends DOMPurify (which we can't use, because it works only in browser).
This PR uses sanitize-html version that doesn't use PostCSS.
Changes:
- Downgrade to `sanitize-html@1.15.0`

Downgrade sanitize-html to version that doesn't use PostCSS

---

src/client/components/Story/Body.less

Fixes #892 
Changes:
- Don't add additional top margin if `img` is first direct child of `p`.

Prevent adding additional margin for images in paragraphs

---

src/client/feed/SubFeed.js

This fixes bug when EmptyFeed message was shown when feed was loading.
Changes:
- Check if is not fetching when showing  EmptyFeed.

Update feed empty check

---

.editorconfig
.prettierignore
.prettierrc.js
scripts/prettier/index.js

Now editor should pick up prettier settings from code directly (so they don't have to be configured manually), and locales shouldn't be autoformatted (by prettier and editorconfig).

Configure scripts

---

src/client/helpers/cryptosHelper.js

Fixes #1525 
Changes:
- If the locale is set to auto we should use navigator language, otherwise, we should use that locale (this causes a crash on Edge).

fix(client): update locale check in charts

---

src/client/components/Story/Story.js

Fixes #1540 
- Ability to control + click  (windows) or command + click (mac) to open new tab for post
Changes:
- add event check for keys pressed while clicking on post title / post preview

Add ability to ctrl/cmd click and open new tab to post

---

src/client/settings/Settings.js
src/client/translations/index.js

Fixes #1039
Changes:
- Re-add chinese traditional to settings
- Use `zh` for react-intl
- See here (All `zh-*` is mapped to zh.js): https://github.com/yahoo/intl-relativeformat/blob/master/dist/locale-data/zh.js

Add Chinese Traditional to Settings

---

src/client/components/Comments/Comment.js

Changes:
- Pass sort key to level 2 comments and down
All comments below the root level were not receiving the sort prop. They were all being sorted by the default prop `BEST`.

Pass Sort Key to sub Comments

---

src/server/handlers/createAmpHandler.js

Sometimes Steem API would take a long time to respond, which caused timeouts.
They weren't properly handled when rendering AMP.

fix: handle timeout on AMP

---

templates/index.html
templates/production_index.html

Fixes #1603 
HTML5Shiv is only relevant to IE8 and lower. React supports IE9+ so we can remove it.

refactor: remove html5shiv

---

src/client/steemAPI.js

I'm having an issue that sounds similar to #1576.
Unfortunately my internet is slow right now.
This has led to find that both Busy client and server have a maximum timeout of 5 seconds. 
[Related issue for rpc.](https://github.com/busyorg/lightrpc/issues/6)

Usability with slow internet

---

src/client/vendor/SanitizeConfig.js

Fixes #1629 
Changes:
- Update regex, so it doesn't match URLs in the format: `https://busy.org.something.else.com`

Update Busy link regex

---

src/client/components/Editor/withEditor.js
src/client/helpers/image.js

Fixes #1568
Changes:
- Upload images to busy-ipfs instead of Cloudinary.
Busy IPFS source code is there at the moment:
https://github.com/Sekhmet/busy-ipfs

feat: migrate to busy-ipfs

---

src/client/components/Navigation/Topnav.js

Fixes:
- go to staging.busy.org on mobile / small screen, and click on search
- search errors out and causes entire page to be blank
Changes:
- update searchInputRef to use the right input due to antd upgrade

Fix for mobile search causing blank screen

---

src/client/components/Editor/Editor.js

Fixes #1666  .
Changes:
- put setBodyAndRender before form error check in `throttledUpdate`

Fix for editor preview not working after tags error

---

src/server/renderers/ssrRenderer.js

Fixes #1687 
Changes:
- This prevents `replace` to interpolate string (see the issue for more).
https://busy.org/@hernandev/project-total-rewards-api-for-utopian-rewards-badges
vs
https://busy-master-pr-1688.herokuapp.com/@hernandev/project-total-rewards-api-for-utopian-rewards-badges

fix: prevent replacement patterns

---

src/client/activity/VoteActionMessage.js

Fixes #1187
Translation keys don't have `_post` suffix.
- Remove `_post` suffix.

fix: use proper translation keys for vote actions

---

src/client/components/PopoverMenu/PopoverMenu.less

Fixes: #1193 
When user menu is launched on small res device it does not take whole screen and it's scrollable, as @Sekhmet described.
* added css rules

Add handling small resolutions for user menu

---

src/client/components/Comments/CommentForm.js
src/client/components/Editor/Editor.js
src/client/components/Editor/EditorInput.js
src/client/settings/ProfileSettings.js

Disable autosize from EditorInput

---

src/client/components/Story/StoryFull.js
src/client/helpers/parser.js
src/client/post/Write/Write.js

Use image alt attribute as lightbox title

---

src/client/helpers/parser.js
src/client/post/Write/Write.js

Fixes #1758.
Changes:
- Use lodash _.get instead of directly calling the array property

Use lodash get in parser.js to fix post breaking

---

src/client/post/Write/Write.js

Fixes #1706.
Busy.org doesn't hijack  ```json_metadata.app``` if a post edited via Busy. This changeset brings priority to busy's default json_metadata tags.
Note: Also, **community** and **format** fields in the json_metadata will have priority and overwritten if they're set before and edited via Busy later on.

Overwrite json_metadata.app when the post edited via Busy. (#1706)

---

src/client/components/Story/StoryFull.less

* Remove cursor pointer from comments h2.
Before:
After:

fix: remove pointer cursor from comments h2

---

package.json
yarn.lock

husky is more popular and has more features (supports all git hooks).
* migrate from pre-commit to husky

chore: migrate from pre-commit to husky

---

package.json
webpack/makeConfig.js
yarn.lock

VisualizerPlugin is no longer supported and shipped with historic React version.
BundleAnalyzerPlugin is active and gives more details about the bundle.
* replace visualizer with bundle analyzer

chore: replace visualizer with bundle analyzer

---

src/client/components/Navigation/Sidenav.js
src/client/components/Sidebar/Topics.less

Fixes #1837 
* remove unnecessary margin from Topics header.
* remove empty `div` that was preventing `:first-child` selector from working.
Before:
After:

fix: update Topics header margins

---

webpack/client.js

Missing hash was likely causing issues with PWA caching styles.
* add missing contenthash to CSS

fix: add missing contenthash to CSS

---

src/client/components/BBackTop.less

Fixes #1861 
* Prevent BBackTop component from blocking screen.

fix: prevent blocking screen

---

src/client/components/Popover.js
src/client/components/PopoverMenu/PopoverMenu.js
src/client/components/PopoverMenu/PopoverMenuItem.js
src/client/components/UserCard.js
src/client/vendor/ReduxInfiniteScroll.js

Some props were failing (PopoverMenu), I updated other as well to use standard `node` proptype.
* Use `node` for children props.

refactor: update prop types

---

src/client/components/Story/Body.js

Fixes #1862 
* rewrite links before sanitisation

fix: rewrite links before sanitisation

---

src/client/components/Editor/Editor.js
src/client/components/Story/Body.js

Fixes #1849 
* Render Preview by Body only.
```
test line
another line
another another
```
Before:
After:

fix: don't render preview to HTML twice

---

src/client/components/Comments/Comment.less

Fixes #1836
- Add parantheses for comment text offset calculations, was breaking due to order of operations

Add parentheses for calculations of comment width offset

---

src/client/components/Comments/CommentForm.js

Fixes #1880 
* Add `preview` prop to Body component.

fix: use BusyIPFS links in comment previews

---

src/client/helpers/image.js

Fixes #1882 
* Check if image URL starts with gateway URL.

fix: don't use proxy for gateway.ipfs.io URLs

---

src/client/components/Comments/CommentForm.js
src/client/components/Editor/Editor.js
src/client/components/Story/Body.js

Fixes #1887 
* Delete code that conditionally updated IPFS links.
* Use default link (ipfs.busy.org)

feat: use BusyIPFS links

---

src/client/post/postsReducer.js

Fixes #1886 
* Ignore `reblogged_by` and `first_reblogged_on` from GET_CONTENT response.

fix: ignore reblogged props from GET_CONTENT

---

src/client/statics/ExitPage.js
src/client/vendor/SanitizeConfig.js

Fixes #1877 
* Use `react-intl` location.
* Add missing hash

fix: preserve hash in ExitPage

---

src/client/wallet/Transfer.js

[deepcrypto8](https://steemit.com/@deepcrypto8) is the deposit account of [Binance](https://binance.com) exchange.
When you try to transfer any SBD/STEEM to exchanges, the interface warns the user that they should put a memo. Binance's deposit account was not listed here, I have added it.
**Before**
**After**

Add binance deposit account to exchange accounts

---

src/client/Wrapper.js
src/client/styles/common.less

Fixes #1809
*  Use 100% instead of 100vw for layout width.
Before:
After:

feat: use 100% width for layout

---

src/client/post/PostModal.js

Fixes #1899 
* Replace post URL instead of adding new entry.

fix: replace post link from modal

---

package.json
src/client/index.js

This removes an unused package `js-logger` was assigned #1812 to other developer but left open 29 days.

Remove unused package js-logger

---

src/client/components/Navigation/Notifications/NotificationTransfer.js

This is the change suggested in #1890.
When user clicks on a received transfer notification send them to the wallet page instead of profile of user who sent the transfer.

Transfer notification link to wallet instead of sender profile

---

src/client/post/Write/Write.js

Fixes #1907 
* Fix bug introduced in #1765
```
dasdasdsa
das
dsa
dsa
dsa
sad
```

fix: extract images

---

src/client/components/Sidebar/PostRecommendationLink.js
src/client/components/Story/StoryPreview.js
src/client/helpers/__tests__/postHelpers.js
src/client/helpers/postHelpers.js
src/client/post/Write/Write.js

Fixes #1953 
* Extract `getContentImages`.
* Use `getContentImages` globally for extracting images.

refactor: extract images from parsed body

---

src/client/feed/feedActions.js

Fixes #1959 
* filter out deleted posts
Before:
After:

fix: filter out deleted posts

---

src/client/styles/common.less

Fixes #1944 
There is compatibility issue on FF that adds transition to height change, which is not desired. This disabled this behaviour.
* Disable transitions on textarea

fix: disable textarea transitions

---

.eslintrc.js
.storybook/config.js
.storybook/webpack.config.js
package.json
src/client/components/Button/Action.js
src/client/components/Button/Action.less
src/client/components/Button/__tests__/Action.js
src/client/components/Button/__tests__/__snapshots__/Action.js.snap
src/client/components/Editor/Editor.js
src/client/components/Icon/Loading.js
src/client/components/QuickPostEditor/QuickPostEditorFooter.js
src/client/components/Sidebar/SidebarWidget.js
src/client/components/Sidebar/SidebarWidget.less
src/client/components/Sidebar/WalletSidebar.js
src/client/components/UserHeader.js
src/client/settings/ProfileSettings.js
src/client/settings/Settings.js
src/client/statics/ExitPage.js
src/client/stories/index.js
src/client/wallet/ClaimRewardsBlock.js
src/client/wallet/__tests__/__snapshots__/UserWalletTransactions.test.js.snap
yarn.lock

Fixes #1804 
Our components are not really that reusable and flexible. We should create gallery of reusable components, that we can use everywhere in the app without unnecessary tweaking. We should over the time improve our components and add it to stories. This will make it easier to test components and features without really implementing them into Busy.org - we should be able to test everything UI/UX related before creating "backend" for this.
* Add `storybooks` scripts.
* Refactor `Action` component to make it more reusable.
* Add `SidebarWidget` component that will be used for all widget blocks we currently have and we will have (#1804).

workflow: add storybooks

---

src/client/discover/Discover.less
src/client/discover/DiscoverUser.js

Fixes #2006 
* Use `ReputationTag` on `Discover` page.

refactor: use ReputationTag on Discover page

---

src/client/user/userActions.js

Fixes #2008 
* Remove additional catch from promise (it should be handled by promise-middleware)

fix: remove additional catch on getFollowing action

---

src/client/components/ReputationTag.js
src/client/stories/index.js

Fixes #2009 
* update ReputationTag props
* Add [story for ReputationTag](https://deploy-preview-2011--peaceful-feynman-099c7f.netlify.com/?selectedKind=ReputationTag&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

fix: update ReputationTag props

---

src/client/components/CommentFooter/Buttons.js
src/client/components/StoryFooter/Payout.js

Fixes #2018 
* Display vote value If it will round up to 0.01 or more.
You would need to find a post that has rewards between 0.05 and 0.01 $ in rewards, which I couldn't find.
https://busy-master-pr-2024.herokuapp.com/@steemitblog/blockchain-update-3-hardfork-20-and-release-19-4-appbase-statsd-and-rocksdb#@tangerinetravels/re-steemitblog-blockchain-update-3-hardfork-20-and-release-19-4-appbase-statsd-and-rocksdb-20180627t210544220z

fix: display payout indicator if value will round up to 0.01

---

src/client/components/Comments/Comments.js

Fixes #2000
* Compare real number of comments.

fix: no comments indicator

---

src/client/feed/feedReducer.js

Fixes #1997
* Properly filter out bookmarks after toggling.
* Don't append old bookmarks on load.

fix: unsaving posts

---

src/client/feed/feedReducer.js

Fixes #2027 
* Fix action types in feedReducer.

fix: loading more feed content

---

src/client/Wrapper.js
src/client/components/BBackTop.js
src/client/post/PostModal.js
src/client/styles/common.less

Fixes #2023 
Current BBackTop logic seems to complicated and it might be confusing for users. Common way back-to-top buttons work is that they show when scrolled below certain threshold. This makes ours work the same way (default logic that BackTop from antd has) to prevent confusion.
* Change BBackTop logic.
* Hide primary BBackTop in post modal (#2023)

update BBackTop logic

---

src/client/activity/UserActionContents.js
src/client/activity/UserActionIcon.js
src/client/activity/UserActionMessage.js
src/common/constants/accountHistory.js

Fixes #1909 
Continuation of https://github.com/busyorg/busy/pull/2015.
- Added a new icon for unfamiliar custom jsons.
- Re-created the PR with the ```develop``` target since the convention is changed. And I wasn't able to update the base branch for the old pull request. 
Now it looks like this:
Not sure about the icon selection, I can change it if there is a better fit.

Fix activity formatting on unfamiliar custom json operations (#1909)

---

src/client/auth/authActions.js

Fixes #2020
Previously action determined if we are refreshing or logging in, based on authenticated prop, which caused another login try when not authenticated.
* refresh login based on loaded, not authenticated prop

fix: refresh login based on loaded, not authenticated prop

---

src/client/helpers/__tests__/errorMiddleware.js
src/common/constants/errors.js

Fixes #2038 
* add UPVOTE_LOCKOUT error fingerprint
It would require to find a post almost 7 days old and to make an upvote that will manage to change rshares of the post. I failed to find such post - added test should suffice though.

fix: add UPVOTE_LOCKOUT error fingerprint

---

src/client/wallet/PowerUpOrDown.js

Fixes #2046 
* Subtract delegated shares from user shares (maximum what user can power down).

fix: subtract delegated_vesting_shares from available shares

---

src/client/post/Write/Write.js

Fixes #2022
* always set current images, links, users and tags (they are always arrays).
Follow how to reproduce steps from the issue using this post as edited post:
https://busy-develop-pr-2048.herokuapp.com/@hellosteem/test-post-with-image

fix: always set current images, links, users and tags

---

src/client/comments/commentsActions.js
src/client/helpers/parser.js
src/client/helpers/postHelpers.js
src/client/post/Write/Write.js

Fixes #2045 
* extract `createPostMetadata` helper.
* unescape links and images (they contain HTML entities after sanitizsation).
* add links, images, and mentions to comments.
```
Links:
https://www.google.com/intl/pl_pl/about/?utm_source=google.com&utm_medium=referral&utm_campaign=hp-footer&fg=1
Mentions:
@sekhmet
```

feat: add create json metadata for comments

---

src/client/components/Sidebar/LastDrafts.js
src/client/post/Write/DraftRow.js
src/client/post/Write/Drafts.js
src/client/types/drafts.js

Fixes #2059 
Draft type is used in many places so I extracted its types to its own file.
* Define stricter prop types.
* Rename `data` to `drafts` in `DraftRow` to make it more clear what it represents.

Update draft types

---

.eslintrc.js

This will allow any mix of LF and CRLF locally, but will fail on CI if CRLF are commited. This basically requires users to configure Git to commit LF (`core.autocrlf true`).

allow mixed line endings locally

---

src/client/components/StoryFooter/Buttons.js

Fixes #2068 
* Display vote count if there is at least one vote.
* Display placeholder for tooltip if there are only downvotes.

feat: display vote count if there is more than one of any vote

---

src/client/comments/Comments.js
src/client/comments/commentsReducer.js
src/client/components/Comments/Comments.js

Fixes #2070 
* Add `isLoaded` prop to comments.
* Call `getComments` for side effects even without comments.
* Display no comments indicator only if comments have been loaded.

fix: don't display no comments message before comments loaded

---

src/client/vendor/SanitizeConfig.js
src/client/vendor/steemitHtmlReady.js

Fixes #2084 
* Properly detect missing protocol.
* Whitelist `byteball` and `bitcoin` protocol (sanitize-html doesn't support disabling this check yet, I submitted PR for this, but I'm not sure if it is desired behaviour).
* Mark non `https?` protocols as external.

Allowed protocols

---

src/common/routes.js

Fixes #2096 
* Only show the editor when you explicitly visit /editor

Only show the editor when you explicitly visit /editor

---

src/common/constants/dmca.json

Fixes 
We got this DMCA takedown notice
```
Cloudflare received a DMCA copyright infringement complaint regarding: 
busy.org 
Below is the complaint we received: 
Reporter's Name: Mark Reyes 
Copyright Holder's Name: 
Reporter's Email Address: report@internetsecurities.org 
Reporter's Company Name: Internet Securities International 
Reporter's Telephone Number: 852 8199 0145 
Reporter's Address: Tsim Sha Tsui, Kowloon, Hong Kong HK 
Reported URLs: 
http://busy.org/@jzeal/ripple-xrp-palm-beach-confidential-teeka-tiwari-s-article-and-breakdown 
http://busy.org/@amitayboneh/this-is-why-cindicator-cnd-worth-5usd-20usd-the-full-pbc-review 
```
Add url's to dmca.json

add new permlinks to dmca.json

---

src/client/comments/commentsActions.js
src/client/comments/commentsReducer.js
src/client/feed/feedReducer.js
src/client/post/postsReducer.js

Still some features might be broken, as "IDs" are not useful at all as identifiers, because many possible IDs are assigned to the same post. We'd need to refactor bunch of code to not use IDs as identifiers.

fix: rename id to post_id

---

src/client/app/Sidebar/RightSidebar.js
src/client/comments/commentsActions.js
src/client/comments/commentsReducer.js
src/client/components/TopicSelector.js
src/client/components/__tests__/TopicSelector.js
src/client/components/__tests__/__snapshots__/TopicSelector.js.snap
src/client/feed/feedReducer.js
src/client/helpers/stateHelpers.js
src/client/locales/default.json
src/client/post/postsReducer.js
src/common/routes.js

- Remove deprecated `active` sorting.
- Use `author/permlink` instead of `post_id` as it is might not be unique right now.

Migrate to new Steemit API

---

src/client/components/Comments/Comment.js
src/client/components/Story/StoryFull.js
src/client/components/StoryFooter/Buttons.js

Fixes #2137
* Enable edit function for posts older than 7 days.
Pick any post older than 7 days
Edit as much as you want :)
Check if it is edited, as below. Simple, right?
It worked like a charm :)
Here is my old post that I actually edit by busy on my local dev server. Of course, the actual edit has been reflected on the real Steem blockchain. https://steemit.com/@blockchainstudio/steem-python-library-sbdtorshares-bugfix
This is my Christmas gift to Steem community :) Hope that it'll be merged soon. Merry Christmas!

edit posts older than 7 days

---

src/client/vendor/steemitHtmlReady.js

Fixes #2105
* Fix the relative url issues. "/@user" and "/@user/permlink" now work!
I made a post for testing. It has various links for testing.

fix relative url

---

src/client/components/Story/Story.js

Fixes #2149
* Fix reblogged_by
`post.first_reblogged_by` returns null. `post.reblogged_by` should be used as follows:
https://github.com/steemit/condenser/blob/7430aca58ae9f86e501f52e3cf8dba5efc9fe3e0/src/app/components/cards/PostSummary.jsx#L70
> Busy.org: my feed (rosatravels isn't my following)
> Steemit.com shows the reblogged information correctly
> **After the fix on my local dev server** 
In addition, to show 'reblogged' in blog (not feed), the current code should be changed. Currently there is no easy way to differentiate if it's feed or blog. But any resteemed post in a blog is easily noticeable by author's name, so not important as reblogged_by in feed.

fix-reblogged-by

---

src/client/comments/Comments.js
src/client/components/Comments/Comment.js
src/client/components/Comments/Comments.js
src/client/components/Story/Body.js
src/client/components/Story/StoryFull.js
src/client/containers/Story/BodyContainer.js
src/client/helpers/constants.js
src/client/helpers/regexHelpers.js
src/client/post/PostContent.js
src/client/vendor/SanitizeConfig.js
src/server/renderers/ssrRenderer.js

* Modify `BodyContainer` so it subscribes for `appUrl`, `rewriteLinks` and `exitPageSetting` (so we don't have to pass it from other parts o the app).
* Only treat relative and same-domain links as internal.
* Remove `localhost` from `knownDomains`.

feat: only open external links as _blank

---

src/client/components/Sidebar/PostRecommendation.js

* Use `author/permlink` as post id, due to API changes.

fix: use username/permlink as a id for post recommendations

---

src/server/handlers/createSsrHandler.js

* Don't pass query string to `matchRoutes`. `matchRoutes` won't match routes correctly if they contain a query string.

fix: don't pass query string to matchRoutes

---

src/client/comments/Comments.js
src/client/comments/commentsActions.js
src/client/comments/commentsReducer.js
src/client/components/CommentFooter/Buttons.js
src/client/components/CommentFooter/CommentFooter.js
src/client/components/Comments/Comment.js
src/client/components/Comments/Comments.js
src/client/helpers/stateHelpers.js

Fixes #2151
* Load comment using `get_content` after replying/editing/upvoting.
* Remove previous `focus` state on old comments.
* Update `pendingVotes`'s `id` type to `string`.

fix: reload comments using get_content

---

src/client/locales/default.json
src/client/wallet/UserWalletSummary.js
src/client/wallet/__tests__/__snapshots__/UserWalletSummary.test.js.snap

* Add missing translation string.
* Use message variables instead of the hard-coded message format.

fix: powering down translation

---

src/client/activity/UserActionIcon.js
src/client/helpers/steemitFormatter.js

* Use `get_state` method instead of `get-state`.
* Use generic icon in case of `custom_json` with unparsable JSON.

fix: activity page

---

src/client/components/StoryFooter/Payout.js

Fixes #2173 
* Show ~~$0.00~~ for payout-declined post all the time
* Show $0.00 or ~~$0.00~~ depending on the declined status even for posts with pending payout lower than $0.005.
https://busy.org/@ned/the-guiding-mission-vision-and-values-of-steemit-inc
> Currently, Busy shows nothing when payout is zero. So it's hard to tell whether it's due to downvoting or decline.
As explained in the proposal, this might be more serious when a post has just been posted. Before voting, no way to tell whether the post is payout-declined or not.
> Busy should show it as ~~$0.00~~ for both posts just posted and paid out.

Show zero payout

---

src/client/components/Utils/USDDisplay.js
src/client/components/__tests__/USSDDisplay.js

Fixes #2175 
* 3-digit precision when 0 < STU < $0.02
* 2-digit precision for all negative values
* negative values always have - sign.
* Test codes are added and modified for these.
> before
> after
> but still 2-digit for >= $0.02
> voting details

Fix 2175: 3-digit precision

---

src/client/components/Editor/Editor.js

Fixes #2194
* Don't show beneficiary setting in the editing mode. (Of course, still showing in the creating mode. Don't worry)
> Currently, regardless of the original beneficiary setting, it is shown as checked (while disabled). This can be quite confusing to normal users even though beneficiary setting can't be changed after the initial posting.
beneficiary setting shouldn't show for editing.

don't show beneficiary setting for editing

---

src/client/components/Navigation/Topnav-nightmode.less

Just some minor CSS fix...
Search for an exact username. The username will be highlighted in the search results.
Before:
After:

fixed background color of highlighted search result in nightmode

---

src/client/vendor/steemitHtmlReady.js

Fix #2197
* Multiple links support in one sentence
Visit https://busy.org/@blockchainstudio/steem-keychain-should-hide-private-keys-by-default

multiple links support in one sentence

---

src/client/components/Editor/Editor.js
src/client/helpers/constants.js

Fixes #2211
To support various SCOT tokens, increase max number of tags to 12.
* max number of tags is now 12 (from 5)
* constant `MAX_TAG` is defined for a change in the future
* intl message with id `topics_error_max_tag` is created
> now support more than 5 tags
> but up to 12 tags

increase tag limit to 12
